// Educational pages maintained outside the historical response-wrapper chain.
// Source checks are recorded in docs/seo-core-guide-release-2026-10-06.md.
export const SOURCE_CHECK_DATE = '2026-10-06';
const NY = 'https://www.tax.ny.gov';
export const SOURCES = {
  introduction: [`${NY}/pubs_and_bulls/tg_bulletins/hut/introduction.htm`, 'TB-HU-40: Introduction to Highway Use Tax'],
  registration: [`${NY}/pubs_and_bulls/tg_bulletins/hut/certificate_of_registration.htm`, 'TB-HU-115: Certificate of Registration'],
  trip: [`${NY}/pubs_and_bulls/tg_bulletins/hut/cor_trip_certificate.htm`, 'TB-HU-116: Trip Certificate'],
  decals: [`${NY}/pubs_and_bulls/tg_bulletins/hut/decals.htm`, 'TB-HU-160: Decals'],
  exemptions: [`${NY}/pubs_and_bulls/tg_bulletins/hut/excluded_and_exempt_vehicles.htm`, 'TB-HU-245: Excluded and Exempt Vehicles'],
  filing: [`${NY}/pubs_and_bulls/tg_bulletins/hut/filing_requirements.htm`, 'TB-HU-260: Filing Requirements'],
  calculation: [`${NY}/pubs_and_bulls/tg_bulletins/hut/how_to_determine_tax.htm`, 'TB-HU-360: How to Determine Your Tax'],
  records: [`${NY}/pubs_and_bulls/tg_bulletins/hut/recordkeeping_requirements.htm`, 'TB-HU-765: Recordkeeping Requirements'],
  instructions: [`${NY}/forms/current-forms/motor/mt903i.htm`, 'Current MT-903 instructions'],
  rates: [`${NY}/e-services/huwf/hutwf_rate_sch1.htm`, 'HUT Schedule 1 tax rates'],
  account: [`${NY}/pdf/current_forms/hut/tmt39_fillin.pdf`, 'Form TMT-39: New Account Application'],
  application: [`${NY}/pdf/current_forms/hut/tmt1_fillin.pdf`, 'Form TMT-1: Certificate and Decal Application']
};
const link = (href, label) => `<a href="${href}">${label}</a>`;
const section = (id, title, body) => ({id, title, body});
const dueDates = `<div class="table-wrap"><table><caption>Standard quarterly HUT deadlines</caption><thead><tr><th scope="col">Reporting period</th><th scope="col">Standard deadline</th></tr></thead><tbody><tr><th scope="row">January–March</th><td>April 30</td></tr><tr><th scope="row">April–June</th><td>July 31</td></tr><tr><th scope="row">July–September</th><td>October 31</td></tr><tr><th scope="row">October–December</th><td>January 31 of the following year</td></tr></tbody></table></div><p>When the deadline is a Saturday, Sunday, or legal holiday, the return is due the next business day. Use your account’s assigned filing frequency.</p>`;

export const CORE_GUIDES = new Map([
  ['/new-york-hut-guide', {
    title: 'New York HUT Permit Guide: Requirements, Cost & Registration',
    heading: 'New York HUT Permit: Complete Guide',
    description: 'Understand New York HUT permit requirements, vehicle weights, registration costs, trip certificates, MT-903 returns, and mileage records.',
    category: 'New York HUT overview',
    answer: 'A New York HUT permit generally means a vehicle’s Highway Use Tax certificate of registration and decal. For covered New York operation, obtain the correct credential before travel, then keep mileage records and file the required returns. An eligible occasional trip can use a HUT trip certificate instead.',
    sections: [
      section('what-is-hut', 'What New York HUT covers', `<p>New York Highway Use Tax is a state mileage tax administered by the Department of Taxation and Finance. It applies to covered vehicles using New York public highways, including trucks based in other states. The registration credential, decal, and recurring tax return serve different purposes.</p><p>HUT does not replace IFTA, IRP plates, insurance, or operating authority. An IFTA decal or apportioned plate does not establish that a truck has HUT credentials. Start with the vehicle’s New York operation, weight, cargo, and any applicable exclusion.</p>`),
      section('who-needs-hut', 'Who needs a HUT permit?', `<p>Under the gross-weight method, the general threshold is <strong>more than 18,000 pounds</strong>, alone or in combination. Gross weight includes the power unit, the heaviest trailer or other drawn device, and the maximum load. It is not simply today’s scale weight.</p><p>Under the unloaded-weight method, the thresholds are <strong>more than 8,000 pounds for a truck</strong> and <strong>more than 4,000 pounds for a tractor</strong>. The carrier’s reporting election matters. A vehicle at exactly 18,000 pounds is not above the gross-weight threshold, but an unloaded-weight election can change the result.</p><p>${link('/learn/how-gvw-affects-your-hut-tax', 'Check the weight definitions and worked examples')} or use the ${link('/tools/hut-permit-requirement', 'permit requirement tool')} for an initial screen.</p>`),
      section('choose-credential', 'Regular registration, trip certificate, or temporary receipt?', `<div class="table-wrap"><table><caption>Choose the credential for the operation</caption><thead><tr><th scope="col">Credential</th><th scope="col">Purpose</th><th scope="col">Follow-up</th></tr></thead><tbody><tr><th scope="row">Regular HUT certificate and decal</th><td>Continuing operation under a carrier’s account</td><td>Maintain vehicle records, mileage records, and assigned returns</td></tr><tr><th scope="row">HUT trip certificate</th><td>Eligible occasional operation for the period printed on the certificate</td><td>Carrier limit of 10 per calendar year; unavailable for automotive-fuel transportation</td></tr><tr><th scope="row">TR-8 temporary credential</th><td>Temporary proof in the regular registration process</td><td>Carry the issued TR-8 while awaiting the certificate and decal; regular filing obligations remain</td></tr></tbody></table></div><p>These are different documents. A payment receipt or an unapproved application is not an issued operating credential. ${link('/guides/get-trip-certificate', 'Read the temporary and trip certificate guide')} before scheduling travel.</p>`),
      section('registration', 'How to prepare for registration', `<p>Match the legal carrier identity and existing account to each vehicle. Gather the legal name and DBA, physical and mailing addresses, taxpayer information, USDOT number when applicable, VIN, plate jurisdiction, year, make, ownership, and weights.</p><p>A new account and a vehicle addition are different requests. New York’s materials identify TMT-39 for new accounts and TMT-1 for HUT/AFC certificates and decals. Existing carriers should check their account before creating another one. ${link('/learn/how-to-register-for-new-york-hut', 'Follow the registration checklist')} and ${link('/form-tmt-1-ny-hut', 'review Form TMT-1')}.</p>`),
      section('cost', 'State fees versus service charges', `<p>New York lists a <strong>$1.50 state fee per vehicle</strong> for a regular HUT or AFC certificate and decal, and a <strong>$25 state fee</strong> for a HUT trip certificate. Those amounts are state credential fees, not a permit company’s total price.</p><p>Service charges and mileage tax are separate. Review the selected service’s price before payment. A regular registration fee does not prepay future HUT mileage tax. An unused trip certificate is not refundable under New York’s trip bulletin.</p>`),
      section('filing-records', 'What happens after regular registration?', `<p>A carrier issued a regular HUT or AFC certificate must file required returns even when no tax is due. New York normally starts accounts quarterly unless it assigns another frequency. ${link('/filing/quarterly-due-dates', 'Check the filing deadlines')} and ${link('/mt-903-filing-center', 'prepare your MT-903 records')}.</p><p>Keep daily vehicle-level trip records and monthly summaries. HUT calculations exclude qualifying toll-paid New York State Thruway miles; not every toll road or bridge is excluded. Retain supporting mileage and toll evidence. The ordinary record-retention period is at least four years from the return’s due date or filing date, whichever is later. Review the ${link('/learning-center/new-york-hut-penalties-and-recordkeeping', 'penalties and recordkeeping primer')} for common compliance mistakes.</p>`),
      section('exemptions', 'Exemptions require the actual vehicle facts', `<p>New York distinguishes excluded vehicles from vehicles used exclusively for an exempt activity. A farm plate, equipment label, or occasional exempt load does not by itself establish an exemption. Changing the use can change the registration and tax treatment.</p><p>Review ${link(SOURCES.exemptions[0], 'New York’s excluded and exempt vehicle definitions')} for the exact operation. For automotive-fuel transportation, review AFC registration; a HUT trip certificate is unavailable for that cargo.</p>`),
      section('examples', 'Two practical starting points', `<p><strong>Recurring interstate tractor-trailer trips:</strong> Check HUT eligibility using the full combination and maximum load, register the correct vehicle under the correct carrier, and establish mileage and return controls.</p><p><strong>One qualifying occasional delivery:</strong> Check trip-certificate eligibility, the carrier’s annual count, cargo, and printed expiry before choosing a trip certificate. One trip does not automatically mean no HUT requirement.</p><p>These examples illustrate the decision process; they are not accounts of individual customers. For an application axle field, see the ${link('/ny-hut-axle-count', 'power-unit axle-count guide')}.</p>`)
    ],
    sources: ['introduction', 'registration', 'trip', 'exemptions', 'filing', 'records'],
    related: [['/learn/how-to-register-for-new-york-hut', 'Registration checklist'], ['/guides/get-trip-certificate', 'Trip certificates and temporary credentials'], ['/mt-903-filing-center', 'MT-903 filing and records']],
    cta: ['https://nyhut.com/ny-hut-permit', 'Continue to NYHUT.com permit service']
  }],
  ['/learn/how-to-register-for-new-york-hut', {
    title: 'How to Register for New York HUT | New York HUT Guide',
    heading: 'How to Register for New York HUT',
    description: 'Prepare a New York HUT account and vehicle application: new versus existing accounts, TMT-39, TMT-1, VINs, weights, credentials, and filing setup.',
    category: 'Registration',
    answer: 'Confirm whether the carrier already has a HUT account, choose the correct vehicle registration request, and obtain the issued credential before covered New York operation. Check the legal entity, VIN, plate, ownership, and weights together; a submitted application alone is not permission to operate.',
    sections: [
      section('account', 'First decide: new account or existing account?', `<p>A carrier account and a vehicle’s credentials are related but separate. New York’s TMT-39 is a new-account application; it says not to use it if you previously registered for HUT. New York also identifies TMT-1 for applying for HUT/AFC certificates and decals.</p><p>Check the legal entity and taxpayer identity before starting. A DBA does not replace the legal name. An ownership or entity change needs review rather than simply reusing another carrier’s account. If New York reports an account discrepancy, resolve the specific notice or delinquency; a second application does not erase it.</p><p>Use the ${link('/hut-registration-center', 'registration center')} and ${link('/form-tmt-1-ny-hut', 'TMT-1 guide')} to identify the request you are preparing.</p>`),
      section('checklist', 'Information to gather before an application', `<div class="table-wrap"><table><caption>Carrier and vehicle preparation checklist</caption><thead><tr><th scope="col">Carrier/account</th><th scope="col">Each vehicle</th></tr></thead><tbody><tr><td>Legal name, DBA, business type, and taxpayer identity</td><td>Complete VIN, unit number, year, make, and fuel type</td></tr><tr><td>Physical street address and separate mailing address when different</td><td>Plate number and issuing state or province</td></tr><tr><td>USDOT number when applicable and contact details</td><td>Truck or tractor classification and ownership or lease details</td></tr><tr><td>Existing HUT account details and any state notices</td><td>Unloaded weight, combination information, and maximum gross weight</td></tr></tbody></table></div><p>Confirm the VIN against the vehicle’s documents, rather than copying it from another unit’s order. Keep an owner’s name available for a leased vehicle. Submit taxpayer IDs, officer information, payments, and documents through the appropriate secure application channel.</p>`),
      section('eligibility', 'Choose the credential before you submit', `<p>Regular registration is generally appropriate for continuing covered operation. An eligible occasional trip may use a trip certificate instead. ${link('/guides/get-trip-certificate', 'Compare a trip certificate with a temporary TR-8 credential')}; they have different expiry and filing consequences.</p><p>For regular applications, review ${link('/learn/how-gvw-affects-your-hut-tax', 'gross and unloaded weight requirements')}. Do not use a CDL threshold, a tractor’s curb weight alone, or trailer axles as substitutes for the required weight and axle fields.</p>`),
      section('workflow', 'Registration and credential checks', `<ol><li><strong>Identify the carrier:</strong> match the legal name and taxpayer identity to the right account.</li><li><strong>Identify the request:</strong> new account, new vehicle, renewal, replacement, or account update.</li><li><strong>Review every vehicle:</strong> confirm VIN, plate, state, ownership, and the intended operating configuration.</li><li><strong>Submit the application:</strong> New York provides state application channels and permits the use of a permit service company. If you want service, continue through NYHUT.com’s secure workflow.</li><li><strong>Review the issued document:</strong> match the carrier, vehicle, and effective information before travel.</li><li><strong>Set up records:</strong> retain the application and confirmation, track New York mileage, and establish the account’s filing calendar.</li></ol>`),
      section('documents', 'Certificate, decal, and temporary credential', `<p>New York says to keep the regular certificate at the carrier’s regular place of business and affix the required decal to the vehicle. The state’s registration bulletin describes carrying an issued TR-8 temporary credential while the certificate and decal are pending. That is different from a generic order receipt.</p><p>A vehicle-specific credential is not a fleet-wide permit. Adding a truck, replacing a decal, changing plates, or acquiring a used truck requires the appropriate review. See ${link('/learn/new-york-hut-certificate-of-registration', 'certificates and decals')} and ${link('/learn/adding-a-vehicle-to-new-york-hut', 'adding a vehicle')}.</p>`),
      section('after-registration', 'Costs and continuing obligations', `<p>The state’s regular certificate and decal fee is $1.50 per vehicle; permit-service charges are additional. Check the actual service selection and total before paying. State approval and document issuance determine when you can use the credential.</p><p>Regular HUT/AFC certificate holders have return obligations even when no tax is due. Registration does not pay future mileage tax or close an old account. Use the ${link('/mt-903-filing-center', 'MT-903 filing center')} to prepare mileage, toll support, and the assigned reporting period.</p><p><strong>Example:</strong> If an existing carrier adds a second tractor, check the existing account, register that tractor’s VIN, review its issued credential, and add it to vehicle-level mileage records. Do not treat the first tractor’s decal as coverage for both.</p>`)
    ],
    sources: ['registration', 'account', 'application', 'decals', 'filing'],
    related: [['/new-york-hut-guide', 'Complete permit guide'], ['/form-tmt-1-ny-hut', 'Form TMT-1'], ['/learn/new-york-hut-certificate-of-registration', 'Certificate and decal guidance']],
    cta: ['https://nyhut.com/ny-hut-permit', 'Prepare a HUT registration at NYHUT.com']
  }],
  ['/guides/get-trip-certificate', {
    title: 'How to Get a New York HUT Trip Certificate | NewYorkHUT.com',
    heading: 'How to Get a New York HUT Trip Certificate',
    description: 'Check New York HUT trip certificate eligibility, the carrier’s annual limit, printed expiration, state fee, fuel restrictions, and temporary TR-8 differences.',
    category: 'Temporary permits and occasional trips',
    answer: 'A qualifying occasional operator can use a vehicle-specific HUT trip certificate instead of regular registration and HUT returns for its covered period. New York limits a carrier to 10 trip certificates per calendar year and excludes automotive-fuel transportation. Obtain it before operation and follow the expiry printed on the certificate.',
    sections: [
      section('trip-or-receipt', 'A trip certificate is different from TR-8', `<div class="table-wrap"><table><caption>Two meanings of a temporary HUT credential</caption><thead><tr><th scope="col">Document</th><th scope="col">What it means</th><th scope="col">Filing consequence</th></tr></thead><tbody><tr><th scope="row">HUT trip certificate</th><td>Time-limited authority for an eligible occasional operation</td><td>No HUT return or mileage tax for that vehicle’s period covered by the certificate</td></tr><tr><th scope="row">TR-8 temporary credential or receipt of application</th><td>Issued temporary proof in the regular HUT/AFC registration process</td><td>Does not remove regular return obligations</td></tr></tbody></table></div><p>A payment confirmation, pending order, or copied document for a different truck is not the same as either issued credential. If you are waiting for a decal, identify the actual document that authorizes the operation.</p>`),
      section('eligibility', 'Who can use a HUT trip certificate?', `<p>Start with the vehicle’s HUT eligibility and expected New York operation. A single delivery can still require a credential. Trip certificates are intended for occasional use; recurring travel usually calls for ${link('/learn/how-to-register-for-new-york-hut', 'regular HUT registration')}.</p><ul><li><strong>Annual count:</strong> the limit is 10 certificates per carrier during a calendar year. Do not assume each truck gets a separate allowance of 10.</li><li><strong>Cargo:</strong> certificates are unavailable for trucks, trailers, dollies, or attached devices transporting automotive fuel.</li><li><strong>Other obligations:</strong> a HUT trip certificate does not replace a fuel-use/IFTA credential, IRP requirements, or operating authority.</li></ul><p>For an automotive-fuel operation, review ${link('/permit-types/automotive-fuel-carrier', 'AFC registration')} before choosing a service.</p>`),
      section('expiration', 'How long is the certificate valid?', `<p>TB-HU-116 describes expiry at <strong>midnight on the third day after issuance</strong>. Use the expiration printed on the issued certificate. Weekends and public holidays do not extend it.</p><p>Do not replace that rule with an assumed rolling 72-hour period, and do not assume a temporary registration receipt has the same duration. Scheduling the order, paying, issuance, and the printed expiry are distinct events.</p><p><strong>Before dispatch:</strong> confirm the planned New York travel is within the issued certificate’s dates. If a trip moves beyond expiry, resolve the credential before the truck operates. An application after travel does not retroactively authorize the earlier trip.</p>`),
      section('prepare', 'What to prepare and check', `<ol><li>Confirm the carrier’s legal identity, existing account if applicable, and calendar-year certificate count.</li><li>Gather the exact vehicle’s VIN, plate and jurisdiction, year, make, type, weight, and ownership details.</li><li>Confirm cargo and the intended travel date before selecting a temporary service.</li><li>Use the appropriate application or service channel and obtain the issued certificate before operation.</li><li>Check the VIN, vehicle details, and printed expiry against the scheduled trip.</li><li>Carry a copy in the vehicle and retain copies for at least four years.</li></ol><p>Use the ${link('/resources/temporary-permit-checklist', 'temporary permit preparation checklist')} to keep the vehicle and trip details together.</p>`),
      section('cost-and-tax', 'State fee, mileage tax, and unused certificates', `<p>New York’s trip certificate state fee is <strong>$25</strong>. A permit service can charge an additional service fee. Verify the service’s full price rather than treating $25 as the total commercial price.</p><p>For the period covered by an eligible HUT trip certificate, the vehicle does not owe HUT mileage tax or require a HUT return for that covered operation. This does not erase a carrier’s separate regular-registration filing obligations. New York does not refund unused trip certificates.</p><p><strong>Example:</strong> A carrier approaching its annual allowance should review regular registration before accepting another New York trip. Buying certificates through different services does not create separate annual allowances.</p>`)
    ],
    sources: ['trip', 'registration', 'filing'],
    related: [['/learn/how-to-register-for-new-york-hut', 'Regular registration'], ['/guides/out-of-state-carriers', 'Out-of-state carriers'], ['/compare/hut-vs-ifta', 'HUT versus IFTA']],
    cta: ['https://nyhut.com/order?product=nyhut-temporary', 'Review temporary permit service at NYHUT.com']
  }],
  ['/learn/how-gvw-affects-your-hut-tax', {
    title: 'How GVW Affects New York HUT Tax | New York HUT Guide',
    heading: 'How GVW Affects New York HUT Tax',
    description: 'Understand HUT gross and unloaded weight, the 18,000-pound threshold, truck and tractor rules, six weight examples, and laden versus unladen rates.',
    category: 'Vehicle weights and tax calculation',
    answer: 'New York HUT uses its own weight definitions. Under the gross-weight method, the general threshold is more than 18,000 pounds. Under the unloaded-weight method, trucks over 8,000 pounds and tractors over 4,000 pounds are covered. The elected method, vehicle configuration, and mileage category determine the calculation.',
    sections: [
      section('definitions', 'Gross weight, unloaded weight, and GVWR', `<p><strong>HUT gross weight</strong> combines the unloaded power unit, the heaviest trailer or other drawn device, and the maximum load to be carried or drawn. The driver and helper are excluded. A combination’s HUT weight is not merely the tractor’s curb weight or a lightly loaded day’s scale ticket.</p><p><strong>Unloaded weight</strong> includes the actual vehicle, its required and permanently attached equipment, equipment used exclusively to protect or load/unload cargo, and full propulsion fuel tanks. It excludes the driver and helper.</p><p><strong>GVWR</strong> is a manufacturer’s rating. Registered weight, GVWR, actual scale weight, unloaded weight, and HUT gross weight are not interchangeable labels. Check the operating configuration and the weight reported on the credential; address an incorrect credential rather than silently changing the tax calculation.</p>`),
      section('thresholds', 'Which threshold applies?', `<div class="table-wrap"><table><caption>General HUT weight thresholds</caption><thead><tr><th scope="col">Method</th><th scope="col">Vehicle</th><th scope="col">Threshold</th></tr></thead><tbody><tr><th scope="row">Gross weight</th><td>Covered truck or tractor, alone or in combination</td><td>More than 18,000 pounds</td></tr><tr><th scope="row">Unloaded weight</th><td>Truck</td><td>More than 8,000 pounds unloaded</td></tr><tr><th scope="row">Unloaded weight</th><td>Tractor</td><td>More than 4,000 pounds unloaded</td></tr></tbody></table></div><p>The gross-weight threshold is strictly above 18,000 pounds. An unloaded-weight election can require credentials for vehicles at or below that gross weight. Exclusions and exempt uses require a separate factual check.</p><p>Choose the reporting method on the first return for the calendar year. New York requires the same method for all vehicles and returns during that year; it cannot be changed until the following year.</p>`),
      section('weight-examples', 'Examples at six common vehicle weights', `<div class="table-wrap"><table><caption>Gross-weight examples, assuming no applicable exclusion or exemption</caption><thead><tr><th scope="col">HUT gross weight</th><th scope="col">What to check</th></tr></thead><tbody><tr><th scope="row">18,000 lb</th><td>Not above the gross-weight threshold; check any unloaded-weight election</td></tr><tr><th scope="row">20,000 lb</th><td>Above the threshold; Schedule 1’s first laden bracket ends at 20,000 lb</td></tr><tr><th scope="row">26,000 lb</th><td>Above the threshold; a CDL classification does not decide HUT treatment</td></tr><tr><th scope="row">40,000 lb</th><td>Include the heaviest drawn device and maximum load in a combination</td></tr><tr><th scope="row">55,000 lb</th><td>HUT applies independently of federal Form 2290; one tax does not replace the other</td></tr><tr><th scope="row">80,000 lb</th><td>Use the full combination; distinguish laden from unladen travel under the gross-weight method</td></tr></tbody></table></div><p>These are screening examples, not payload limits or a conclusion that every vehicle in the weight group is taxable. See ${link('/learn/form-2290-heavy-vehicle-use-tax', 'Form 2290 guidance')} for the separate federal tax.</p>`),
      section('rates', 'How weight changes the tax calculation', `<p>Tax is taxable New York mileage multiplied by the applicable rate. The gross-weight method offers straight-line and heaviest-weight options. Under the straight-line option, use each vehicle’s laden and unladen mileage in the appropriate categories; do not apply the laden rate to all travel.</p><p><strong>Illustrative laden calculation:</strong> Schedule 1 lists $0.0084 per mile at 20,000 pounds and $0.0546 per mile at 80,000 pounds. For 100 taxable laden miles, those rates produce $0.84 and $5.46 respectively. This illustration assumes ordinary Schedule 1 treatment and is not a complete return calculation.</p><p>Tractors with trailers have a separate unladen table from trucks and tractors without trailers. The unloaded-weight method also has separate truck and tractor tables. Check the ${link(SOURCES.rates[0], 'official rate schedule')} rather than using one fleet-wide rate by habit.</p>`),
      section('records-and-changes', 'Records, trailers, and weight changes', `<p>Keep vehicle-level daily trip records, monthly totals, and support for laden/unladen travel. Qualifying toll-paid New York State Thruway miles are excluded from taxable mileage; retain the evidence. Not all toll-paid roads qualify.</p><p>Before changing the weight used for a vehicle, reconcile the credential and supporting equipment records. ${link('/learn/changing-gvw-on-a-new-york-hut-vehicle', 'Review vehicle weight changes')}. Axle count is a separate application field: ${link('/ny-hut-axle-count', 'count power-unit axles for the NYHUT.com application')} rather than using a tractor-trailer total.</p><p>Keep the registration, vehicle documents, tax-method election, and mileage records consistent. The ${link('/tools/hut-tax-estimator', 'HUT tax estimator')} can help with planning; the applicable state instructions govern a filed return.</p>`)
    ],
    sources: ['registration', 'introduction', 'calculation', 'rates', 'records'],
    related: [['/learn/who-needs-a-new-york-hut-permit', 'Who needs HUT'], ['/learn/how-to-register-for-new-york-hut', 'Register a vehicle'], ['/mt-903-filing-center', 'Prepare mileage for filing']],
    cta: ['https://nyhut.com/ny-hut-permit', 'Prepare vehicle information at NYHUT.com']
  }],
  ['/mt-903-filing-center', {
    title: 'New York HUT Filing & MT-903 Guide | NewYorkHUT.com',
    heading: 'MT-903 Filing Center',
    description: 'Prepare New York HUT returns with filing requirements, no-tax returns, deadlines, mileage and toll records, leased vehicles, amended returns, and final returns.',
    category: 'Filing and recordkeeping',
    answer: 'A carrier issued a regular HUT or AFC certificate must file required HUT returns even when no tax is due or another person will pay it. Confirm the assigned filing frequency, gather vehicle-level mileage and toll support, and use the correct original, amended, or final return. Eligible HUT trip certificates have a separate covered-period exception.',
    sections: [
      section('who-files', 'Who must file an MT-903 return?', `<p>MT-903 is New York’s paper Highway Use Tax return. New York also provides electronic filing. A regular HUT/AFC certificate holder’s filing obligation does not disappear because a truck stayed outside New York, had no taxable miles, or another person pays the tax.</p><p>A HUT trip certificate has different treatment: the vehicle’s covered operation does not require a HUT return or mileage tax for that period. Do not apply that exception to a regular certificate or TR-8 temporary registration credential.</p><p>See ${link('/learn/who-must-file-mt-903', 'who must file')} and ${link('/guides/get-trip-certificate', 'trip certificates versus regular credentials')}.</p>`),
      section('filing-deadlines', 'Reporting periods and deadlines', dueDates + `<p>Accounts normally begin quarterly unless the Tax Department assigns another period. Later reclassification depends on prior-year HUT liability and the state’s notice. ${link('/filing/quarterly-due-dates', 'Review quarterly, monthly, and annual filing rules')} before preparing the return.</p>`),
      section('records', 'Build the return from vehicle-level records', `<ol><li><strong>Confirm the account and period:</strong> use the correct legal entity, reporting dates, and assigned frequency.</li><li><strong>Reconcile vehicles:</strong> match credentials, VINs, plates, ownership, and lease arrangements.</li><li><strong>Compile daily trips:</strong> keep dates, origin/destination, New York and outside-New-York mileage, and toll-paid Thruway mileage.</li><li><strong>Apply the method:</strong> distinguish laden and unladen mileage where required, and use the correct vehicle/weight rate category.</li><li><strong>Reconcile support:</strong> retain trip records, toll evidence, bills of lading, and monthly vehicle summaries.</li><li><strong>Retain filing evidence:</strong> keep the completed return, applicable schedules, payment confirmation, and supporting records together.</li></ol><p>Ordinary HUT records must be retained for at least four years from the due date or filing date, whichever is later. Records must be kept in New York unless the Tax Department consents to their removal. Hard-copy or electronic records must support the entries on the return. See ${link('/filing/record-retention', 'record-retention guidance')} for keeping the supporting documents together.</p>`),
      section('mileage-example', 'Example: New York miles are not always taxable miles', `<p>Suppose a trip record shows 150 New York miles, of which 100 are documented qualifying toll-paid Thruway miles. The remaining 50 miles are the starting point for taxable mileage, subject to the vehicle’s method and applicable treatment. Do not subtract every toll-road mile simply because a toll was paid.</p><p>If the 50 taxable miles include both loaded and empty travel, preserve that split for the applicable gross-weight tables. A fleet-wide fuel receipt or a remembered round number cannot replace the vehicle’s trip evidence. See ${link('/learn/new-york-hut-taxable-miles', 'taxable mileage')} and ${link('/learn/hut-recordkeeping-requirements', 'recordkeeping requirements')}.</p>`),
      section('return-types', 'No activity, amended, and final returns', `<ul><li><strong>No activity:</strong> file the required no-tax-due return for the period. An inactive quarter does not automatically close the account.</li><li><strong>Amended:</strong> correct a previously filed period using the amended-return designation, the full corrected figures rather than just the difference, and an explanation of changes.</li><li><strong>Final:</strong> use this when permanently discontinuing the business for HUT purposes. Follow New York’s instructions for surrendering certificates and decals, addressing bills, and filing delinquent returns.</li></ul><p>Do not mark a return final just because one truck had no miles or was sold. ${link('/learn/amended-final-and-no-activity-mt-903-returns', 'Read the return-type guide')} and ${link('/new-york-hut/how-do-i-close-a-new-york-hut-account', 'account closure guidance')} for the distinct steps.</p>`),
      section('leases-and-filing', 'Leased vehicles and filing support', `<p>Determine whose certificate is used and who reports the vehicle and mileage. A lessor’s and lessee’s filing obligations depend on their certificates and the arrangement; paying tax for someone else does not automatically remove their return requirement. Review ${link('/filing/leased-vehicles', 'leased-vehicle reporting')}.</p><p>For preparation support, review ${link('/filing/web-file', 'filing methods')}, ${link('/resources/trip-record-checklist', 'trip-record checklist')}, ${link('/filing/audit-support', 'audit support')}, and the ${link('/forms-library', 'HUT forms library')}. Verify your submitted return against the current state instructions and retain submission evidence.</p>`)
    ],
    sources: ['filing', 'instructions', 'records', 'calculation', 'trip'],
    related: [['/filing/quarterly-due-dates', 'Deadlines and filing frequency'], ['/learn/new-york-hut-taxable-miles', 'Taxable miles'], ['/learn/amended-final-and-no-activity-mt-903-returns', 'Amended, final, and no-activity returns']],
    cta: ['https://nyhut.com/my-nyhut', 'Continue to MyNYHUT for filing preparation']
  }],
  ['/filing/quarterly-due-dates', {
    title: 'New York HUT Quarterly Due Dates | NewYorkHUT.com',
    heading: 'New York HUT Quarterly Due Dates',
    description: 'Check New York HUT quarterly due dates, weekend and holiday adjustments, monthly and annual reclassification, and no-activity filing obligations.',
    category: 'MT-903 deadlines and frequency',
    answer: 'Standard quarterly HUT deadlines are April 30, July 31, October 31, and January 31 of the following year. A Saturday, Sunday, or legal-holiday deadline moves to the next business day. Confirm whether New York has assigned your account quarterly, monthly, or annual filing.',
    sections: [
      section('quarterly-calendar', 'Quarterly reporting calendar', dueDates + `<p>The return covers the preceding reporting period. For example, July–September activity belongs on the third-quarter return, not the October–December return.</p><p><strong>2026 third quarter:</strong> October 31, 2026 falls on Saturday, so the next-business-day rule makes the deadline <strong>Monday, November 2, 2026</strong>. The standard October 31 label in a recurring table must be checked against the actual year.</p>`),
      section('frequency', 'How filing frequency can change', `<p>After a calendar year of quarterly filing, New York reviews the preceding year’s HUT liability and notifies the carrier of a change. Do not select annual filing simply because this quarter’s bill is small.</p><div class="table-wrap"><table><caption>Reclassification thresholds effective for periods from January 1, 2022</caption><thead><tr><th scope="col">Preceding calendar-year HUT liability</th><th scope="col">Filing treatment</th></tr></thead><tbody><tr><th scope="row">$1,200 or less</th><td>Annual if subject to HUT for the entire preceding calendar year</td></tr><tr><th scope="row">More than $1,200 through $12,000</th><td>Quarterly</td></tr><tr><th scope="row">More than $12,000</th><td>Monthly</td></tr></tbody></table></div><p>Use the Tax Department’s assigned frequency and notice. The annual-filing rule includes the entire-prior-year condition; it is not a shortcut for a newly opened account.</p>`),
      section('monthly-annual', 'Monthly and annual deadlines', `<p>A monthly return is due on the last day of the following month, subject to the same weekend and legal-holiday adjustment. For example, September activity has a standard October 31 deadline.</p><p>An annual return for January–December has a standard January 31 deadline in the following year, again adjusted when necessary. Check the current MT-903 instructions and the reporting period assigned to the account before filing.</p>`),
      section('no-tax', 'No New York miles does not automatically mean no return', `<p>A carrier with a regular HUT or AFC certificate must file required returns even when no tax is due. Another person paying the vehicle’s tax does not by itself remove the certificate holder’s filing obligation. A HUT trip certificate has a separate covered-period exception.</p><p>An amended return corrects an already filed period. A final return concerns permanent discontinuation for HUT purposes; it is not the same as a no-activity quarter. See ${link('/learn/amended-final-and-no-activity-mt-903-returns', 'return types')} before choosing either designation.</p>`),
      section('prepare', 'Prepare before the deadline', `<ol><li>Confirm the account’s assigned frequency and exact reporting period.</li><li>Reconcile each credentialed vehicle’s daily trips and monthly totals.</li><li>Separate taxable mileage and supported qualifying Thruway mileage.</li><li>Apply the elected tax method and correct rates.</li><li>File and pay by the adjusted deadline, then retain confirmation and source records.</li></ol><p>Use the ${link('/mt-903-filing-center', 'MT-903 filing center')}, ${link('/tools/mt903-due-date', 'due-date calculator')}, ${link('/tools/filing-deadlines', 'filing calendar planner')}, and ${link('/learn/hut-recordkeeping-requirements', 'recordkeeping guide')} for preparation. Resolve account notices rather than assuming a missing reminder extends the deadline.</p>`)
    ],
    sources: ['filing', 'instructions'],
    related: [['/mt-903-filing-center', 'MT-903 filing center'], ['/learn/who-must-file-mt-903', 'Who must file'], ['/learn/amended-final-and-no-activity-mt-903-returns', 'No-activity and corrected returns']],
    cta: ['https://nyhut.com/my-nyhut', 'Prepare your filing in MyNYHUT']
  }]
]);

const escape = value => String(value).replace(/&/g, '&amp;').replace(/"/g, '&quot;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
export function renderCoreGuide(path) {
  const page = CORE_GUIDES.get(path);
  if (!page) return null;
  const canonical = `https://newyorkhut.com${path}`;
  const schema = {'@context':'https://schema.org','@type':'Article',headline:page.heading,description:page.description,
    mainEntityOfPage:canonical,dateModified:SOURCE_CHECK_DATE,
    author:{'@type':'Organization',name:'NewYorkHUT.com',url:'https://newyorkhut.com/about'},
    publisher:{'@type':'Organization',name:'NewYorkHUT.com',url:'https://newyorkhut.com/'},
    citation:page.sources.map(key=>SOURCES[key][0])};
  const cta = new URL(page.cta[0]);
  for (const [key, value] of Object.entries({utm_source:'newyorkhut.com',utm_medium:'referral',utm_campaign:'authority_site',utm_content:path.slice(1)})) cta.searchParams.set(key, value);
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${escape(page.title)}</title><meta name="description" content="${escape(page.description)}"><link rel="canonical" href="${canonical}"><meta property="og:title" content="${escape(page.title)}"><meta property="og:description" content="${escape(page.description)}"><meta property="og:url" content="${canonical}"><meta property="og:type" content="article"><script type="application/ld+json">${JSON.stringify(schema).replace(/</g,'\\u003c')}</script><style>
  :root{font-family:Inter,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;color:#18324a;background:#fff}*{box-sizing:border-box}body{margin:0;line-height:1.7}a{color:#075eae;text-underline-offset:3px}a:focus-visible{outline:3px solid #e2a925;outline-offset:3px}.wrap{width:min(1000px,calc(100% - 36px));margin:auto}.skip{position:absolute;left:10px;top:-80px;background:#fff;padding:12px;z-index:2}.skip:focus{top:10px}.core-header{background:#082b4c;color:#fff;padding:18px 0}.core-header .wrap{display:flex;align-items:center;justify-content:space-between;gap:20px;flex-wrap:wrap}.core-header a{color:#fff;text-decoration:none}.brand{font-size:1.25rem;font-weight:900}.core-header nav{display:flex;gap:16px;flex-wrap:wrap}.hero{padding:42px 0 24px;background:#f3f8fc;border-bottom:1px solid #d7e3ed}.eyebrow{font-size:.8rem;font-weight:800;letter-spacing:.06em;text-transform:uppercase;color:#436079}h1{font-size:clamp(2rem,5vw,3.2rem);line-height:1.15;margin:12px 0 18px;color:#082b4c}.answer{font-size:1.1rem;max-width:850px}.byline{font-size:.88rem;color:#526b80}.contents{padding:22px;border:1px solid #d7e3ed;border-radius:10px;background:#fbfdff;margin:30px 0}.contents ol{columns:2;padding-left:22px}.contents li{break-inside:avoid;margin:6px 0}article{padding:0 0 40px}section[id]{scroll-margin-top:20px;margin:34px 0}h2{font-size:1.5rem;line-height:1.3;color:#082b4c}li{margin:.5rem 0}.table-wrap{overflow-x:auto;margin:20px 0}table{border-collapse:collapse;width:100%;font-size:.95rem}caption{text-align:left;font-weight:800;padding:0 0 10px}th,td{padding:12px 14px;border:1px solid #cfdee9;text-align:left;vertical-align:top}thead{background:#eef5fa}.source-note,.service{padding:22px;border:1px solid #d7e3ed;border-radius:10px;background:#f6f9fc}.source-note{font-size:.95rem}.cta{display:inline-block;background:#1768c5;color:#fff;text-decoration:none;font-weight:800;padding:12px 18px;border-radius:8px}.related{padding:20px 0}.related a{display:block;margin:8px 0}@media(max-width:650px){.contents ol{columns:1}.core-header nav{gap:12px;font-size:.9rem}.hero{padding-top:28px}th,td{padding:10px}}
  </style></head><body><a class="skip" href="#main">Skip to guide</a><header id="nyh-global-header" class="core-header"><div class="wrap"><a class="brand" href="/">NewYorkHUT.com</a><nav aria-label="Primary navigation"><a href="/new-york-hut-guide">Permit guide</a><a href="/learn">Learn</a><a href="/tools">Tools</a><a href="/services">Services</a><a href="/ask-hut-ai">Ask HUT AI</a><a href="/site-map">All Pages</a><a href="/mt-903-filing-center">MT-903 filing</a><a href="/about">About</a></nav></div></header><main id="main"><div class="hero"><div class="wrap"><div class="eyebrow">${page.category}</div><h1>${page.heading}</h1><p class="answer">${page.answer}</p><p class="byline">Published by <a href="/about">NewYorkHUT.com</a> · Official sources checked <time datetime="${SOURCE_CHECK_DATE}">October 6, 2026</time></p></div></div><article class="wrap"><nav class="contents" aria-label="In this guide"><strong>In this guide</strong><ol>${page.sections.map(s=>`<li><a href="#${s.id}">${s.title}</a></li>`).join('')}</ol></nav>${page.sections.map(s=>`<section id="${s.id}"><h2>${s.title}</h2>${s.body}</section>`).join('')}<section class="source-note" id="official-sources"><h2>Official sources and scope</h2><ul>${page.sources.map(key=>`<li>${link(...SOURCES[key])}</li>`).join('')}</ul><p>This guide summarizes the linked New York sources for preparation and education. Examples are illustrative. Check the current instructions and your account’s notices for your operation. NewYorkHUT.com is an independent resource within the Compliance University educational framework and is not a New York State agency.</p></section><section class="related" aria-label="Related guidance"><h2>Related guidance</h2>${page.related.map(([href,label])=>link(href,label)).join('')}</section><section class="service"><h2>Need help with the next step?</h2><p>NYHUT.com handles service requests, sensitive carrier and vehicle information, payment, and customer document access. Review the selected service and price before submitting.</p><a class="cta" href="${escape(cta.toString())}">${page.cta[1]}</a></section></article></main></body></html>`;
}
