import site from "./index-v19.js";
const ORDER="https://nyhut.com/";
const FILING={
"filing-requirements":["New York HUT Filing Requirements","A carrier issued a permanent HUT or AFC certificate generally must file returns even when no tax is due.","Permanent credentials create continuing filing duties until the account is properly closed or the Tax Department changes the filing requirement."],
"quarterly-due-dates":["New York HUT Quarterly Due Dates","Initial HUT filing is generally quarterly: April 30, July 31, October 31, and January 31 for the preceding calendar quarter.","The Tax Department may later reclassify an account to monthly or annual filing based on prior-year liability."],
"zero-activity-returns":["HUT Zero-Activity and No-Tax Returns","No New York mileage or no tax due does not automatically eliminate the return requirement for permanent registrants.","File the required no-activity return and retain confirmation rather than assuming silence closes the period."],
"web-file":["How to Web File a New York HUT Return","New York HUT Web File can calculate amounts, accept payment, and provide an electronic confirmation.","Use the current certificate number for every vehicle reported and verify the account filing frequency displayed by the system."],
"amended-and-final-returns":["Amended and Final HUT Returns","Corrections and business closure require the correct amended or final-return workflow.","A final return does not erase prior bills or delinquencies, and certificates may need to be returned to the HUT Registration Unit."],
"leased-vehicles":["Leased Vehicles and HUT Reporting","The owner and lessee must determine whose certificate is being used and who reports the vehicle mileage.","The certificate under which the vehicle operates controls the reporting workflow; ownership alone does not settle the issue."],
"daily-trip-records":["Daily HUT Trip Record Requirements","Each registered truck or tractor needs daily mileage records supporting taxable and nontaxable New York operation.","Records should identify the certificate, plate, VIN, owner when leased, trip dates, origins, destinations, routes, and mileage."],
"record-retention":["How Long to Keep New York HUT Records","HUT records generally must be retained for at least four years from the return due date or filing date, whichever is later.","Electronic records are acceptable when they contain enough detail to verify returns and determine the proper tax."],
"audit-support":["HUT Audit Support and Mileage Reconstruction","Weak source records can lead to reconstructed mileage and assessments.","Keep trip sheets, dispatch records, toll evidence, odometer data, vehicle files, returns, payments, and reconciliation schedules together."]};
const FAQ={
"who-needs-hut":["Who needs a New York HUT permit?","A qualifying motor vehicle operating on New York public highways may need HUT credentials based on weight, configuration, use, and any valid exemption."],
"hut-threshold":["What is the New York HUT weight threshold?","The general gross-weight threshold is more than 18,000 pounds, but unloaded-weight elections and specialized facts require separate analysis."],
"ifta-replace-hut":["Does IFTA replace New York HUT?","No. IFTA addresses fuel-tax allocation; New York HUT is a separate highway-use tax and credential obligation."],
"irp-replace-hut":["Does IRP registration replace New York HUT?","No. IRP apportions registration fees and does not independently satisfy New York HUT requirements."],
"one-trip":["Do I need HUT for one trip into New York?","A qualifying occasional trip may use a vehicle-specific trip certificate, subject to eligibility and cargo restrictions."],
"trip-certificate-limit":["Can I keep using HUT trip certificates?","Trip certificates are intended for occasional operation, not as a permanent substitute for recurring New York travel."],
"no-miles-return":["Do I file a HUT return when there are no New York miles?","Permanent registrants generally still file the required no-activity or zero-tax return."],
"how-long-records":["How long must HUT records be kept?","Records generally must be kept at least four years from the due date or filing date of the related return, whichever is later."],
"decal-transfer":["Can a New York HUT decal be moved to another truck?","Vehicle-specific credentials should not be transferred without authorization; replacements and fleet changes must remain tied to the correct VIN and account."],
"farm-exemption":["Are farm trucks exempt from New York HUT?","Some narrowly defined farm operations may qualify, but farm ownership or agricultural work alone does not create a blanket exemption."],
"tow-truck-exemption":["Are tow trucks exempt from New York HUT?","Not automatically. A tow truck must be evaluated by weight, design, and actual use; it is not necessarily an excluded truck crane."],
"automotive-fuel":["Can an automotive-fuel carrier use a HUT trip certificate?","The ordinary HUT trip-certificate workflow is not available for vehicles transporting automotive fuel."]};
const C=`:root{--n:#082b4c;--b:#1768c5;--l:#dbe5ef;font-family:Inter,system-ui,sans-serif}*{box-sizing:border-box}body{margin:0;color:#122033;line-height:1.65}.w{width:min(1120px,calc(100% - 36px));margin:auto}.top{background:var(--n);color:#fff;padding:8px 0}header{background:#fff;border-bottom:1px solid var(--l);position:sticky;top:0;z-index:10}nav{min-height:72px;display:flex;justify-content:space-between;align-items:center;gap:18px}.brand,.links a,.btn{text-decoration:none}.brand{font-weight:900}.links{display:flex;gap:14px;align-items:center;font-weight:750}.btn{display:inline-flex;background:var(--b);color:#fff;padding:11px 16px;border-radius:10px;font-weight:850}.hero{padding:60px 0 48px;background:linear-gradient(#f9fcff,#edf5fb)}h1{font-size:clamp(2.5rem,5vw,4.4rem);line-height:1;letter-spacing:-.045em;color:var(--n);margin:12px 0 18px}h2,h3{color:var(--n)}.lead{font-size:1.15rem;color:#4e6074;max-width:850px}.crumb{font-size:.9rem;color:#5b6b7e}.crumb a,.card a,.side a{color:var(--b);text-decoration:none}.eye{font-size:.78rem;text-transform:uppercase;letter-spacing:.1em;font-weight:900;color:var(--b)}section{padding:62px 0}.grid{display:grid;grid-template-columns:repeat(3,1fr);gap:20px}.card,.side,.fact div{border:1px solid var(--l);border-radius:16px;padding:23px}.card{display:flex;flex-direction:column}.card p{color:#5b6b7e;flex:1}.article{display:grid;grid-template-columns:minmax(0,760px) 280px;gap:44px}.fact{display:grid;grid-template-columns:1fr 1fr;gap:14px;margin:24px 0}.note{background:#fff8e5;border-left:4px solid #f4b83f;padding:17px;margin:24px 0}.side{position:sticky;top:92px;height:max-content}.side a{display:block;font-weight:750;margin:10px 0}.cta{background:var(--n);color:#fff;border-radius:18px;padding:30px;margin-top:34px}.cta h2{color:#fff}footer{background:#071d33;color:#b7c6d6;padding:38px 0}@media(max-width:950px){.grid{grid-template-columns:1fr 1fr}.article{grid-template-columns:1fr}.side{position:static}.links a:not(.btn){display:none}}@media(max-width:620px){.grid,.fact{grid-template-columns:1fr}.w{width:min(100% - 24px,1120px)}h1{font-size:2.55rem}}`;
function H(){return `<div class="top"><div class="w">Independent New York HUT guidance</div></div><header><nav class="w"><a class="brand" href="/">NewYorkHUT.com</a><div class="links"><a href="/filing">Filing</a><a href="/faq">FAQ</a><a href="/tools">Tools</a><a href="/resources">Resources</a><a class="btn" href="${ORDER}">Start Permit</a></div></nav></header>`}
function F(){return `<footer><div class="w"><strong>NewYorkHUT.com</strong><p>Private guidance and permit assistance. Not affiliated with New York State.</p></div></footer>`}
function L(t,d,p,b,s=""){return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${t}</title><meta name="description" content="${d}"><meta name="robots" content="index,follow"><link rel="canonical" href="https://newyorkhut.com${p}"><meta property="og:title" content="${t}"><meta property="og:description" content="${d}"><style>${C}</style>${s}</head><body>${H()}${b}${F()}</body></html>`}
function hub(kind,data,title,lead){const cards=Object.entries(data).map(([s,v])=>`<article class="card"><h2>${v[0]}</h2><p>${v[1]}</p><a href="/${kind}/${s}">Read answer →</a></article>`).join("");return L(title,lead,`/${kind}`,`<main><section class="hero"><div class="w"><div class="crumb"><a href="/">Home</a> / ${title}</div><div class="eye">Authority center</div><h1>${title}</h1><p class="lead">${lead}</p></div></section><section><div class="w grid">${cards}</div></section></main>`,`<script type="application/ld+json">${JSON.stringify({"@context":"https://schema.org","@type":"CollectionPage","name":title,"url":`https://newyorkhut.com/${kind}`})}</script>`)}
function filingPage(s){const v=FILING[s],p=`/filing/${s}`,rel=Object.entries(FILING).filter(([x])=>x!==s).slice(0,6).map(([x,y])=>`<a href="/filing/${x}">${y[0]}</a>`).join("");const schema={"@context":"https://schema.org","@graph":[{"@type":"Article","headline":v[0],"description":v[1],"mainEntityOfPage":`https://newyorkhut.com${p}`},{"@type":"BreadcrumbList","itemListElement":[{"@type":"ListItem","position":1,"name":"Home","item":"https://newyorkhut.com/"},{"@type":"ListItem","position":2,"name":"Filing","item":"https://newyorkhut.com/filing"},{"@type":"ListItem","position":3,"name":v[0],"item":`https://newyorkhut.com${p}`}]}]};return L(v[0],v[1],p,`<main><section class="hero"><div class="w"><div class="crumb"><a href="/">Home</a> / <a href="/filing">Filing</a> / ${v[0]}</div><div class="eye">Filing and recordkeeping guide</div><h1>${v[0]}</h1><p class="lead">${v[1]}</p></div></section><section><div class="w article"><article><div class="fact"><div><strong>Core rule</strong><p>${v[2]}</p></div><div><strong>Control point</strong><p>Verify the account filing frequency, certificate status, reporting method, vehicle list, and source records before submission.</p></div></div><h2>Recommended workflow</h2><ol><li>Confirm the reporting period and due date.</li><li>Reconcile every active vehicle and certificate.</li><li>Compile daily trip and mileage source records.</li><li>Separate taxable, excluded, and documented toll-paid mileage.</li><li>File, pay, and retain the confirmation with supporting schedules.</li></ol><div class="note"><strong>Do not rely on memory.</strong> The filed return should reconcile to vehicle-level source documents and the account's current filing frequency.</div><div class="cta"><h2>Need permit or account assistance?</h2><a class="btn" href="/tools/service-finder">Service Finder</a> <a class="btn" href="${ORDER}">Start Permit</a></div></article><aside class="side"><h3>Related filing topics</h3>${rel}<h3>Resources</h3><a href="/resources/trip-record-checklist">Trip checklist</a><a href="/resources/audit-readiness-checklist">Audit checklist</a><a href="/faq">HUT FAQ</a></aside></div></section></main>`,`<script type="application/ld+json">${JSON.stringify(schema)}</script>`)}
function faqPage(s){const v=FAQ[s],p=`/faq/${s}`,rel=Object.entries(FAQ).filter(([x])=>x!==s).slice(0,7).map(([x,y])=>`<a href="/faq/${x}">${y[0]}</a>`).join("");const schema={"@context":"https://schema.org","@type":"FAQPage","mainEntity":[{"@type":"Question","name":v[0],"acceptedAnswer":{"@type":"Answer","text":v[1]}}]};return L(v[0],v[1],p,`<main><section class="hero"><div class="w"><div class="crumb"><a href="/">Home</a> / <a href="/faq">FAQ</a> / ${v[0]}</div><div class="eye">New York HUT FAQ</div><h1>${v[0]}</h1><p class="lead">${v[1]}</p></div></section><section><div class="w article"><article><h2>What to verify</h2><p>The final answer can depend on vehicle weight, configuration, ownership, actual use, cargo, trip frequency, account status, reporting election, and any valid exemption or exclusion.</p><div class="note"><strong>Use the exact vehicle facts.</strong> Similar trucks operated by the same company can require different credentials or reporting treatment.</div><h2>Next step</h2><p>Use the eligibility wizard for screening, review the related authority center, or continue to secure permit ordering.</p><div class="cta"><a class="btn" href="/tools/eligibility-wizard">Eligibility Wizard</a> <a class="btn" href="${ORDER}">Start Permit</a></div></article><aside class="side"><h3>More questions</h3>${rel}</aside></div></section></main>`,`<script type="application/ld+json">${JSON.stringify(schema)}</script>`)}
function S(base,data){const u=[`/${base}`,...Object.keys(data).map(x=>`/${base}/${x}`)];return `<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${u.map(x=>`<url><loc>https://newyorkhut.com${x}</loc><changefreq>monthly</changefreq></url>`).join("")}</urlset>`}
const HH={"content-type":"text/html; charset=UTF-8","cache-control":"public, max-age=300"};
export default{async fetch(r,e,c){const p=new URL(r.url).pathname.replace(/\/+$/g,"")||"/";if(p==="/filing")return new Response(hub("filing",FILING,"New York HUT Filing and Recordkeeping","Return deadlines, Web File, zero-activity returns, leased vehicles, daily trip records, record retention, and audit support."),{headers:HH});if(p==="/faq")return new Response(hub("faq",FAQ,"New York HUT Frequently Asked Questions","Clear answers to the permit, weight, filing, trip-certificate, exemption, decal, IFTA, and IRP questions carriers ask most often."),{headers:HH});if(p==="/sitemap-filing.xml")return new Response(S("filing",FILING),{headers:{"content-type":"application/xml; charset=UTF-8"}});if(p==="/sitemap-faq.xml")return new Response(S("faq",FAQ),{headers:{"content-type":"application/xml; charset=UTF-8"}});if(p.startsWith("/filing/")){const s=p.split("/").pop();if(FILING[s])return new Response(filingPage(s),{headers:HH});}if(p.startsWith("/faq/")){const s=p.split("/").pop();if(FAQ[s])return new Response(faqPage(s),{headers:HH});}return site.fetch(r,e,c)}};