import site from "./index-v24.js";
const ORDER="https://nyhut.com/";
const SERIES={
"registration-series":["New York HUT Registration Series","HUT certificates and decals are issued for a defined registration series. Carriers should confirm the active series before placing credentials in service.","Match every active certificate and decal to the correct series, account, vehicle, and VIN."],
"renewal-preparation":["Prepare for New York HUT Renewal","Renewal preparation should begin with account standing, filing status, balances, contact information, and a complete active-fleet reconciliation.","Resolve missing returns, notices, sold vehicles, duplicate units, and account changes before renewal."],
"fleet-reconciliation":["HUT Fleet Reconciliation","A fleet reconciliation compares the carrier's real operating fleet with every active HUT or AFC certificate and decal.","Verify VIN, plate, weight, ownership, status, credential number, and registration series for each unit."],
"inactive-vehicles":["Inactive, Sold, and Retired HUT Vehicles","Vehicles removed from service should be clearly separated from the active credential and filing process.","Document disposition dates, preserve historical records, and prevent old credentials from being reused on another vehicle."],
"series-transition":["Transitioning to a New HUT Registration Series","A new registration series requires controlled replacement of prior-series credentials across the active fleet.","Issue, install, verify, and document new credentials before retiring prior-series materials."],
"renewal-problems":["Common HUT Renewal Problems","Unfiled returns, balances, outdated addresses, vehicle mismatches, and unresolved notices can disrupt renewal.","Review the complete account rather than treating renewal as a decal-only transaction."]};
const ACCOUNT={
"legal-name-change":["Changing a Legal Name on a HUT Account","A legal-name change should be coordinated across the taxpayer account, carrier records, filing access, vehicles, and correspondence.","Retain formation, amendment, merger, assumed-name, and tax-identity documents supporting the change."],
"address-change":["Changing a HUT Account Address","Update physical, mailing, recordkeeping, and notice addresses so credentials and tax correspondence reach the correct location.","Confirm which address controls official notices and preserve proof of the completed update."],
"ownership-change":["HUT Account Ownership Changes","A sale, merger, conversion, or taxpayer-identity change may require more than editing an existing account.","Determine whether the legal taxpayer remains the same before moving vehicles or credentials."],
"contact-access":["HUT Contacts and Online Access","Maintain current authorized contacts, email addresses, telephone numbers, and online filing access.","Remove former employees and verify that at least two responsible people can access filing records and notices."],
"close-account":["How to Close a New York HUT Account","Closing an account requires final filing, balance review, credential disposition, and retained proof of closure.","Do not assume inactivity, vehicle sales, or an expired registration series automatically closes filing obligations."],
"vehicle-master-list":["Maintain a HUT Vehicle Master List","A controlled vehicle master list connects each VIN to its plate, weight, ownership, credential, status, and filing responsibility.","Use one authoritative list and record effective dates for every addition, removal, replacement, and correction."],
"account-audit":["Annual HUT Account Audit","An annual internal audit can identify missing returns, old vehicles, incorrect addresses, credential mismatches, and access problems before enforcement or renewal.","Reconcile account, fleet, filing, payment, notice, and recordkeeping data in one review."]};
const CSS=`:root{--n:#082b4c;--b:#1768c5;--l:#dbe5ef;--g:#f4b83f;font-family:Inter,system-ui,sans-serif}*{box-sizing:border-box}body{margin:0;color:#122033;line-height:1.65}.w{width:min(1120px,calc(100% - 36px));margin:auto}.top{background:var(--n);color:#fff;padding:8px 0}header{background:#fff;border-bottom:1px solid var(--l);position:sticky;top:0;z-index:10}nav{min-height:72px;display:flex;justify-content:space-between;align-items:center;gap:18px}.brand,.links a,.btn{text-decoration:none}.brand{font-weight:900}.links{display:flex;gap:13px;align-items:center;font-weight:750}.btn{display:inline-flex;background:var(--b);color:#fff;padding:11px 16px;border-radius:10px;font-weight:850}.hero{padding:60px 0 48px;background:linear-gradient(#f9fcff,#edf5fb)}h1{font-size:clamp(2.45rem,5vw,4.3rem);line-height:1;letter-spacing:-.045em;color:var(--n);margin:12px 0 18px}h2,h3{color:var(--n)}.lead{font-size:1.15rem;color:#4e6074;max-width:850px}.crumb{font-size:.9rem;color:#5b6b7e}.crumb a,.card a,.side a{color:var(--b);text-decoration:none}.eye{font-size:.78rem;text-transform:uppercase;letter-spacing:.1em;font-weight:900;color:var(--b)}section{padding:62px 0}.grid{display:grid;grid-template-columns:repeat(3,1fr);gap:20px}.card,.side,.fact div{border:1px solid var(--l);border-radius:16px;padding:23px}.card{display:flex;flex-direction:column}.card p{color:#5b6b7e;flex:1}.article{display:grid;grid-template-columns:minmax(0,760px) 280px;gap:44px}.fact{display:grid;grid-template-columns:1fr 1fr;gap:14px;margin:24px 0}.note{background:#fff8e5;border-left:4px solid var(--g);padding:17px;margin:24px 0}.side{position:sticky;top:92px;height:max-content}.side a{display:block;font-weight:750;margin:10px 0}.cta{background:var(--n);color:#fff;border-radius:18px;padding:30px;margin-top:34px}.cta h2{color:#fff}footer{background:#071d33;color:#b7c6d6;padding:38px 0}@media(max-width:950px){.grid{grid-template-columns:1fr 1fr}.article{grid-template-columns:1fr}.side{position:static}.links a:not(.btn){display:none}}@media(max-width:620px){.grid,.fact{grid-template-columns:1fr}.w{width:min(100% - 24px,1120px)}h1{font-size:2.5rem}}`;
function H(){return `<div class="top"><div class="w">Independent New York HUT guidance</div></div><header><nav class="w"><a class="brand" href="/">NewYorkHUT.com</a><div class="links"><a href="/registration-series">Renewal</a><a href="/account-management">Account</a><a href="/guides">Guides</a><a href="/official-resources">Official Resources</a><a class="btn" href="${ORDER}">Start Permit</a></div></nav></header>`}
function F(){return `<footer><div class="w"><strong>NewYorkHUT.com</strong><p>Private guidance and permit assistance. Not affiliated with New York State.</p></div></footer>`}
function L(t,d,p,b,s=""){return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${t}</title><meta name="description" content="${d}"><meta name="robots" content="index,follow"><link rel="canonical" href="https://newyorkhut.com${p}"><meta property="og:title" content="${t}"><meta property="og:description" content="${d}"><style>${CSS}</style>${s}</head><body>${H()}${b}${F()}</body></html>`}
function hub(base,data,title,lead){const cards=Object.entries(data).map(([s,v])=>`<article class="card"><h2>${v[0]}</h2><p>${v[1]}</p><a href="/${base}/${s}">Open guide →</a></article>`).join("");return L(title,lead,`/${base}`,`<main><section class="hero"><div class="w"><div class="crumb"><a href="/">Home</a> / ${title}</div><div class="eye">Account control center</div><h1>${title}</h1><p class="lead">${lead}</p></div></section><section><div class="w grid">${cards}</div></section></main>`,`<script type="application/ld+json">${JSON.stringify({"@context":"https://schema.org","@type":"CollectionPage","name":title,"url":`https://newyorkhut.com/${base}`})}</script>`)}
function page(base,data,s){const v=data[s],p=`/${base}/${s}`,rel=Object.entries(data).filter(([x])=>x!==s).slice(0,6).map(([x,y])=>`<a href="/${base}/${x}">${y[0]}</a>`).join("");const schema={"@context":"https://schema.org","@type":"Article","headline":v[0],"description":v[1],"mainEntityOfPage":`https://newyorkhut.com${p}`};return L(v[0],v[1],p,`<main><section class="hero"><div class="w"><div class="crumb"><a href="/">Home</a> / <a href="/${base}">${base==="registration-series"?"Registration Series":"Account Management"}</a> / ${v[0]}</div><div class="eye">Operational control guide</div><h1>${v[0]}</h1><p class="lead">${v[1]}</p></div></section><section><div class="w article"><article><div class="fact"><div><strong>Primary control</strong><p>${v[2]}</p></div><div><strong>Evidence to retain</strong><p>Keep submissions, confirmations, notices, vehicle records, effective dates, issued credentials, and internal review notes together.</p></div></div><h2>Recommended workflow</h2><ol><li>Identify the exact legal entity and account.</li><li>Reconcile current filing, payment, notice, and vehicle status.</li><li>Document the requested change and its effective date.</li><li>Update every affected credential, record, and responsible person.</li><li>Verify completion and preserve proof.</li></ol><div class="note"><strong>Do not update one system in isolation.</strong> Account, vehicle, credential, filing, payment, and correspondence records should remain consistent.</div><div class="cta"><h2>Need account or permit assistance?</h2><a class="btn" href="/services/account-update">Account Update Help</a> <a class="btn" href="${ORDER}">Start Permit</a></div></article><aside class="side"><h3>Related topics</h3>${rel}<h3>Supporting centers</h3><a href="/guides/renew-registration">Renewal guide</a><a href="/filing">Filing and records</a><a href="/official-resources">Official resources</a></aside></div></section></main>`,`<script type="application/ld+json">${JSON.stringify(schema)}</script>`)}
function map(base,data){const u=[`/${base}`,...Object.keys(data).map(x=>`/${base}/${x}`)];return `<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${u.map(x=>`<url><loc>https://newyorkhut.com${x}</loc><changefreq>monthly</changefreq></url>`).join("")}</urlset>`}
const MAPS=["sitemap-guides.xml","sitemap-vehicles.xml","sitemap-weight.xml","sitemap-exemptions.xml","sitemap-cost.xml","sitemap-tools.xml","sitemap-resources.xml","sitemap-industries.xml","sitemap-permit-types.xml","sitemap-university.xml","sitemap-states.xml","sitemap-comparisons.xml","sitemap-filing.xml","sitemap-faq.xml","sitemap-violations.xml","sitemap-calculators.xml","sitemap-assistant.xml","sitemap-services.xml","sitemap-glossary.xml","sitemap-official-resources.xml","sitemap-registration-series.xml","sitemap-account-management.xml"];
const HH={"content-type":"text/html; charset=UTF-8","cache-control":"public, max-age=300"};
export default{async fetch(r,e,c){const p=new URL(r.url).pathname.replace(/\/+$/g,"")||"/";if(p==="/registration-series")return new Response(hub("registration-series",SERIES,"New York HUT Registration Series and Renewal","Plan certificate-series transitions, renewal preparation, fleet reconciliation, inactive vehicles, and common renewal corrections."),{headers:HH});if(p.startsWith("/registration-series/")){const s=p.split("/").pop();if(SERIES[s])return new Response(page("registration-series",SERIES,s),{headers:HH})}if(p==="/account-management")return new Response(hub("account-management",ACCOUNT,"New York HUT Carrier Account Management","Maintain accurate legal, address, ownership, contact, closure, vehicle-master, and annual account-control records."),{headers:HH});if(p.startsWith("/account-management/")){const s=p.split("/").pop();if(ACCOUNT[s])return new Response(page("account-management",ACCOUNT,s),{headers:HH})}if(p==="/sitemap-registration-series.xml")return new Response(map("registration-series",SERIES),{headers:{"content-type":"application/xml; charset=UTF-8"}});if(p==="/sitemap-account-management.xml")return new Response(map("account-management",ACCOUNT),{headers:{"content-type":"application/xml; charset=UTF-8"}});if(p==="/sitemap.xml")return new Response(`<?xml version="1.0" encoding="UTF-8"?><sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${MAPS.map(x=>`<sitemap><loc>https://newyorkhut.com/${x}</loc></sitemap>`).join("")}</sitemapindex>`,{headers:{"content-type":"application/xml; charset=UTF-8"}});return site.fetch(r,e,c)}};