import site from './index-v58.js';

const VERSION='v59';
const ORDER='https://www.nyhut.com/';
const ASK='/ask-hut-ai';
const OFFICIAL='https://www.tax.ny.gov/pubs_and_bulls/tg_bulletins/hut/certificate_of_registration.htm';

const CSS=`<style id="nyh-v59-lifecycle-css">
:root{--n:#082b4c;--b:#1768c5;--l:#d7e3ed;--m:#5b6f83;--p:#f3f8fc;--y:#fff8df;font-family:Inter,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}*{box-sizing:border-box}body{margin:0;color:#13263a;line-height:1.58}.w{width:min(1160px,calc(100% - 40px));margin:auto}header{position:sticky;top:0;z-index:9999;background:#fff;border-bottom:1px solid var(--l);box-shadow:0 4px 18px rgba(8,43,76,.06)}.nav{min-height:76px;display:flex;align-items:center;justify-content:space-between;gap:18px}.brand{font-weight:950;color:var(--n);text-decoration:none;font-size:1.15rem}.links{display:flex;gap:8px;flex-wrap:wrap}.links a{padding:9px 13px;border:1px solid #b8cad9;border-radius:10px;text-decoration:none;color:var(--n);font-weight:850}.links .order{background:var(--b);color:#fff;border-color:var(--b)}.hero{padding:58px 0 44px;background:linear-gradient(135deg,#f9fcff,#eaf4fc)}h1{font-size:clamp(2.3rem,5vw,4rem);line-height:1.03;letter-spacing:-.04em;color:var(--n);margin:10px 0 16px}h2,h3{color:var(--n)}.lead{max-width:900px;color:#496078;font-size:1.08rem}.eyebrow{font-size:.76rem;text-transform:uppercase;letter-spacing:.09em;font-weight:900;color:var(--b)}.section{padding:48px 0 72px}.grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:20px}.card,.panel{border:1px solid var(--l);border-radius:20px;padding:24px;background:#fff;box-shadow:0 10px 34px rgba(8,43,76,.06)}.card p,.card li{color:var(--m)}.btn{display:inline-flex;align-items:center;justify-content:center;margin:10px 8px 0 0;padding:12px 16px;border-radius:10px;background:var(--b);color:#fff;text-decoration:none;font-weight:900}.secondary{background:#fff;color:var(--b);border:1px solid var(--b)}.notice{background:var(--y);border-left:4px solid #e2a500;padding:16px;border-radius:8px;margin:20px 0}.steps{padding-left:22px}.steps li{margin:10px 0}.related{display:flex;gap:10px;flex-wrap:wrap;margin-top:20px}.related a{padding:9px 12px;border:1px solid var(--l);border-radius:999px;text-decoration:none;color:var(--n);font-weight:800}.source{background:var(--p);border:1px solid #cfe0ee;border-radius:18px;padding:22px;margin-top:24px}.faq details{border-bottom:1px solid var(--l);padding:14px 0}.faq summary{font-weight:850;color:var(--n);cursor:pointer}@media(max-width:800px){.grid{grid-template-columns:1fr}.nav{display:block;padding:12px 0}.brand{display:block;margin-bottom:10px}.links{display:grid;grid-template-columns:repeat(2,1fr)}.links a{text-align:center}.links .order{grid-column:1/-1}.w{width:min(100% - 24px,1160px)}}
</style>`;

function header(){return `<header><div class="w nav"><a class="brand" href="/">NewYorkHUT.com</a><nav class="links" aria-label="Primary navigation"><a href="/learn">Learn</a><a href="/vehicle-lifecycle">Vehicle Changes</a><a href="/tools">Tools</a><a href="/services">Services</a><a href="${ASK}">Ask HUT AI</a><a class="order" href="${ORDER}">Go to NYHUT</a></nav></div></header>`}
function shell(title,description,path,body){return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${title}</title><meta name="description" content="${description}"><link rel="canonical" href="https://newyorkhut.com${path}">${CSS}</head><body>${header()}${body}</body></html>`}
function related(){return `<div class="related"><a href="/vehicle-lifecycle">Vehicle Lifecycle Hub</a><a href="/tools/hut-permit-requirement">Permit Wizard</a><a href="/tools/hut-rate-lookup">Rate Lookup</a><a href="${ASK}">Ask HUT AI</a><a href="${ORDER}">Open NYHUT</a></div>`}

const pages={
'/learn/buying-a-new-york-hut-permitted-truck':{title:'Buying a New York HUT-Permitted Truck',desc:'What buyers should do before and after purchasing a truck previously registered for New York HUT.',quick:'The seller’s HUT credential does not transfer to you. Confirm tax clearance, complete the ownership transfer, and obtain a new HUT credential under your own account before taxable New York operation.',steps:['Ask the seller for the applicable HUT tax-clearance documentation before closing.','Confirm the VIN, title, plate plan, and intended registered weight.','Do not use the seller’s HUT certificate or decal.','Complete title and registration transfer requirements.','Apply for a new HUT certificate and decal under your own account.','Begin mileage records when you take control of the vehicle.'],mistakes:['Assuming the decal stays with the truck.','Buying before confirming tax clearance.','Operating in New York before the buyer’s credential is issued.']},
'/learn/replacing-a-new-york-hut-truck':{title:'Replacing a New York HUT Truck',desc:'How to remove an old truck and place a replacement truck into New York HUT service.',quick:'Treat the outgoing and replacement trucks as separate vehicles. Close out the old truck correctly and obtain a credential for the replacement truck using its own VIN, plate, and registered weight.',steps:['Record the old truck’s final in-service date and mileage.','Cancel or remove the old vehicle credential when control ends.','Remove and surrender the old decal when required.','Add the replacement vehicle using the correct VIN, plate, and GVW.','Obtain a new certificate and decal for the replacement truck.','Keep records linking the fleet change to the correct filing quarter.'],mistakes:['Moving the old decal to the replacement truck.','Using the old truck’s weight or plate information.','Losing the old truck’s final mileage records.']},
'/learn/adding-a-vehicle-to-your-new-york-hut-account':{title:'Adding a Vehicle to a New York HUT Account',desc:'Checklist for adding another truck or tractor to an existing New York HUT account.',quick:'Each qualifying vehicle needs its own accurate credential record. Add the vehicle before taxable New York operation and verify the VIN, plate, registered weight, and filing method.',steps:['Confirm the vehicle will operate on New York public highways.','Determine the correct registered gross weight.','Gather VIN, plate, ownership, and fleet information.','Add the vehicle through the applicable registration process.','Confirm the certificate and decal match the vehicle.','Add the vehicle to mileage and quarterly filing records.'],mistakes:['Using an estimated rather than registered weight.','Reusing another vehicle’s decal.','Failing to add the vehicle to quarterly mileage tracking.']},
'/learn/removing-a-vehicle-from-your-new-york-hut-account':{title:'Removing a Vehicle from a New York HUT Account',desc:'How to remove a sold, retired, destroyed, or otherwise inactive truck from a New York HUT account.',quick:'Remove the vehicle credential when you no longer control or operate the truck, preserve final mileage records, and keep the account open if other HUT vehicles remain active.',steps:['Document why and when the vehicle left service.','Record final taxable and other reportable mileage.','Cancel the vehicle credential through the appropriate process.','Remove and surrender the decal when required.','Retain sale, destruction, retirement, or transfer records.','Continue filing for any remaining active vehicles.'],mistakes:['Closing the entire account when only one truck is removed.','Discarding records needed for the final quarter.','Leaving the decal on a sold or retired vehicle.']},
'/learn/changing-your-registered-gross-vehicle-weight':{title:'Changing Your Registered Gross Vehicle Weight for HUT',desc:'What to review when a truck’s registered gross vehicle weight changes for New York HUT purposes.',quick:'A GVW change can affect the vehicle’s HUT rate and credential information. Update the vehicle record before relying on a new weight and use the correct rate for the applicable period.',steps:['Confirm the legal and operational reason for the weight change.','Determine the new registered gross weight.','Update the vehicle credential through the applicable process.','Verify the revised certificate information.','Use the new rate only for the correct effective period.','Keep documentation supporting the change.'],mistakes:['Changing only an internal fleet record.','Using the new rate before the credential change is effective.','Confusing GVWR, registered weight, and actual operating weight.']},
'/learn/lost-new-york-hut-certificate':{title:'Lost New York HUT Certificate',desc:'Steps to take when a New York HUT certificate is lost, damaged, or unavailable.',quick:'Do not substitute another vehicle’s certificate. Confirm the vehicle record, request a replacement through the appropriate HUT process, and retain proof of the replacement request.',steps:['Confirm which vehicle and certificate are affected.','Verify VIN, plate, account, and GVW information.','Request a replacement credential through the applicable process.','Keep confirmation and replacement records.','Review whether operation is permitted while replacement is pending.'],mistakes:['Using a certificate from another truck.','Requesting replacement with incorrect plate or VIN data.','Failing to keep proof of the replacement request.']},
'/learn/lost-new-york-hut-decal':{title:'Lost or Damaged New York HUT Decal',desc:'What to do when a New York HUT decal is lost, damaged, destroyed, or unreadable.',quick:'A missing or unusable decal should be addressed through the official replacement process. Do not move a decal from another vehicle or create an unofficial substitute.',steps:['Confirm the decal is lost, damaged, destroyed, or unreadable.','Verify the associated VIN, plate, and credential.','Request a replacement decal through the applicable HUT process.','Keep proof of the request and issuance.','Install the replacement on the correct vehicle.'],mistakes:['Borrowing another truck’s decal.','Continuing indefinitely without replacement.','Failing to document why the original decal is unavailable.']}
};

function guide(path,data){const body=`<main><section class="hero"><div class="w"><div class="eyebrow">Vehicle lifecycle guide</div><h1>${data.title}</h1><p class="lead">${data.quick}</p></div></section><section class="section"><div class="w"><div class="grid"><article class="card"><h2>Quick answer</h2><p>${data.quick}</p><h2>Step-by-step</h2><ol class="steps">${data.steps.map(x=>`<li>${x}</li>`).join('')}</ol></article><article class="card"><h2>Common mistakes</h2><ul>${data.mistakes.map(x=>`<li>${x}</li>`).join('')}</ul><div class="notice"><strong>Important:</strong> Vehicle facts and timing matter. Confirm the current New York requirements before operating or transferring ownership.</div><a class="btn" href="${ORDER}">Complete this task in NYHUT →</a><a class="btn secondary" href="${ASK}">Ask HUT AI →</a></article></div><div class="source"><h2>Official reference</h2><p>Review the New York Tax Department’s current HUT certificate and vehicle credential guidance before acting.</p><a class="btn" href="${OFFICIAL}" target="_blank" rel="noopener">View official guidance →</a>${related()}</div></div></section></main>`;return shell(`${data.title} | NewYorkHUT.com`,data.desc,path,body)}

function hub(){const cards=[
['Buying a Truck','/learn/buying-a-new-york-hut-permitted-truck','Tax clearance, ownership transfer, and a new credential under the buyer’s account.'],
['Selling or Transferring a Truck','/learn/selling-or-transferring-a-new-york-hut-permitted-truck','Cancel the old credential, remove the decal, report final mileage, and address tax clearance.'],
['Replacing a Truck','/learn/replacing-a-new-york-hut-truck','Close out the old vehicle and place the replacement truck into service correctly.'],
['Adding a Vehicle','/learn/adding-a-vehicle-to-your-new-york-hut-account','Add a new truck to an existing HUT fleet with accurate VIN, plate, and GVW data.'],
['Removing a Vehicle','/learn/removing-a-vehicle-from-your-new-york-hut-account','Remove sold, retired, destroyed, or inactive vehicles without closing the entire account.'],
['Changing GVW','/learn/changing-your-registered-gross-vehicle-weight','Understand how a registered weight change affects the credential and tax rate.'],
['Lost Certificate','/learn/lost-new-york-hut-certificate','Request a replacement and avoid using another vehicle’s certificate.'],
['Lost or Damaged Decal','/learn/lost-new-york-hut-decal','Use the official replacement process and keep proof of the request.']
];const body=`<main><section class="hero"><div class="w"><div class="eyebrow">New York HUT vehicle changes</div><h1>Vehicle Lifecycle Center</h1><p class="lead">Use these guides whenever a truck is bought, sold, replaced, added, removed, reweighted, or missing a HUT document.</p></div></section><section class="section"><div class="w"><div class="grid">${cards.map(c=>`<article class="card"><h2>${c[0]}</h2><p>${c[2]}</p><a class="btn" href="${c[1]}">Open guide →</a></article>`).join('')}</div><div class="source"><h2>Move from guidance to action</h2><p>Use NewYorkHUT.com to understand the requirement, then complete permit, fleet, and filing tasks in NYHUT.</p><a class="btn" href="${ORDER}">Open NYHUT Compliance Center →</a><a class="btn secondary" href="${ASK}">Ask HUT AI →</a>${related()}</div></div></section></main>`;return shell('New York HUT Vehicle Lifecycle Center','Guides for buying, selling, replacing, adding, removing, reweighting, and replacing HUT vehicle documents.','/vehicle-lifecycle',body)}

function injectLinks(html){if(html.includes('Vehicle Lifecycle Center'))return html;const block=`<section class="panel" style="margin:24px auto;width:min(1100px,calc(100% - 40px))"><h2>Vehicle changes and fleet guidance</h2><p>Buying, selling, replacing, adding, removing, or reweighting a truck?</p><a class="btn" href="/vehicle-lifecycle">Open Vehicle Lifecycle Center →</a></section>`;let out=html;if(!out.includes('nyh-v59-lifecycle-css'))out=out.replace(/<\/head>/i,`${CSS}</head>`);return out.replace(/<\/main>/i,`${block}</main>`)}

export default{async fetch(request,env,ctx){const url=new URL(request.url);const path=url.pathname.replace(/\/+$/,'')||'/';if(path==='/vehicle-lifecycle')return new Response(hub(),{headers:{'content-type':'text/html; charset=utf-8','cache-control':'no-store','x-newyorkhut-version':VERSION,'x-newyorkhut-feature':'vehicle-lifecycle-hub-v59'}});if(pages[path])return new Response(guide(path,pages[path]),{headers:{'content-type':'text/html; charset=utf-8','cache-control':'no-store','x-newyorkhut-version':VERSION,'x-newyorkhut-feature':'vehicle-lifecycle-guides-v59'}});const response=await site.fetch(request,env,ctx);if((path==='/learn'||path==='/ask-hut-ai')&&(response.headers.get('content-type')||'').includes('text/html')){const headers=new Headers(response.headers);headers.set('cache-control','no-store');headers.set('x-newyorkhut-version',VERSION);return new Response(injectLinks(await response.text()),{status:response.status,headers})}return response}};