import site from "./index-v17.js";
const ORDER="https://nyhut.com/";
const PERMITS={
"permanent-hut-registration":["Permanent HUT Registration","Vehicle-specific registration for carriers expecting recurring New York operation.","Best suited to ongoing or repeated operation, but it creates continuing account, return, payment, mileage-record, and fleet-maintenance responsibilities."],
"hut-trip-certificate":["HUT Trip Certificate","A temporary vehicle-specific credential for qualifying occasional New York operation.","Trip certificates should be obtained before operation and are not a substitute for permanent registration when usage becomes recurring or exceeds applicable limits."],
"automotive-fuel-carrier":["Automotive Fuel Carrier Registration","A specialized registration workflow for vehicles transporting automotive fuel in New York.","Automotive-fuel transport requires separate analysis and does not use the ordinary HUT trip-certificate workflow."],
"replacement-certificate-decal":["Replacement Certificate or Decal","A replacement workflow for credentials that are lost, damaged, destroyed, or otherwise unusable.","The replacement must remain tied to the correct account, vehicle, VIN, and credential history."],
"additional-vehicle-registration":["Adding a Vehicle to an Existing HUT Account","A fleet-expansion workflow for registering another vehicle under an established carrier account.","Adding a unit requires complete vehicle identity, ownership, weight, configuration, and reporting-method data; an existing account does not automatically cover the new vehicle."],
"account-update":["HUT Account and Business Information Updates","A maintenance workflow for legal-name, address, contact, ownership, or fleet changes.","Business changes should be reconciled across taxpayer, carrier, vehicle, credential, and filing records rather than updated in only one location."],
"renewal-series":["HUT Registration Renewal and New Series","The periodic process of reconciling the carrier account and active fleet for a new registration series.","Renewal should include account-status review, vehicle reconciliation, unresolved return or balance issues, and retirement of obsolete credentials."]
};
const COURSES={
"hut-foundations":["HUT Foundations","Learn what the Highway Use Tax is, which operations trigger review, and how weight, vehicle type, and New York highway use interact.",["Separate HUT from IFTA, IRP, CDL, and federal heavy-vehicle tax","Identify the carrier, vehicle, combination, and New York operation","Understand gross-weight and unloaded-weight reporting methods","Recognize when exemptions or exclusions require deeper review"]],
"vehicle-and-weight-analysis":["Vehicle and Weight Analysis","Build a repeatable method for classifying trucks, tractors, trailers, buses, and specialized equipment.",["Identify the power unit and drawn device","Determine maximum combination weight","Distinguish registered, actual, gross, and unloaded weight","Document vehicle design and actual use"]],
"credentials-and-permits":["Credentials and Permit Selection","Choose between permanent registration, trip certificates, AFC workflows, replacements, and account updates.",["Match the credential to the exact vehicle","Compare occasional and recurring operation","Identify automotive-fuel restrictions","Control replacements, additions, and renewals"]],
"mileage-and-recordkeeping":["Mileage and Recordkeeping","Create trip-level support for taxable mileage, laden and unladen operation, and valid mileage exclusions.",["Capture trip dates, routes, origins, and destinations","Record odometer or hubometer readings","Separate laden and unladen mileage when required","Retain toll and source documentation"]],
"returns-and-payments":["Returns, Payments, and Account Status","Understand recurring filing duties, zero-activity periods, payment controls, and account reconciliation.",["Confirm filing frequency and due dates","File required returns even when no tax is due","Reconcile payments and notices","Resolve late filings, interest, penalties, and account holds"]],
"audit-readiness":["Audit Readiness","Organize credentials, vehicle records, returns, payments, trip support, and exemption evidence before an inquiry begins.",["Build a vehicle-and-credential history","Tie reported totals to source documents","Retain exemption and exclusion evidence","Document corrections and amended returns"]]
};
const C=`:root{--n:#082b4c;--b:#1768c5;--l:#dbe5ef;--s:#f4f8fc;font-family:Inter,system-ui,sans-serif}*{box-sizing:border-box}body{margin:0;color:#122033;line-height:1.65}.w{width:min(1120px,calc(100% - 36px));margin:auto}.top{background:var(--n);color:#fff;padding:8px 0}header{background:#fff;border-bottom:1px solid var(--l);position:sticky;top:0;z-index:10}nav{min-height:72px;display:flex;justify-content:space-between;align-items:center;gap:16px}.brand,.links a,.btn{text-decoration:none}.brand{font-weight:900}.links{display:flex;gap:13px;align-items:center;font-weight:750}.btn{display:inline-flex;background:var(--b);color:#fff;padding:11px 16px;border-radius:10px;font-weight:850}.hero{padding:60px 0 48px;background:linear-gradient(#f9fcff,#edf5fb)}h1{font-size:clamp(2.5rem,5vw,4.4rem);line-height:1;letter-spacing:-.045em;color:var(--n);margin:12px 0 18px}h2,h3{color:var(--n)}.lead{font-size:1.15rem;color:#4e6074;max-width:850px}.crumb{font-size:.9rem;color:#5b6b7e}.crumb a,.card a,.side a{color:var(--b);text-decoration:none}.eye{font-size:.78rem;text-transform:uppercase;letter-spacing:.1em;font-weight:900;color:var(--b)}section{padding:62px 0}.grid{display:grid;grid-template-columns:repeat(3,1fr);gap:20px}.card,.side,.lesson{border:1px solid var(--l);border-radius:16px;padding:23px}.card{display:flex;flex-direction:column}.card p{color:#5b6b7e;flex:1}.article{display:grid;grid-template-columns:minmax(0,760px) 280px;gap:44px}.side{position:sticky;top:92px;height:max-content}.side a{display:block;font-weight:750;margin:10px 0}.note{background:#fff8e5;border-left:4px solid #f4b83f;padding:17px;margin:24px 0}.lesson{margin:14px 0;background:#fff}.cta{background:var(--n);color:#fff;border-radius:18px;padding:30px;margin-top:34px}.cta h2{color:#fff}footer{background:#071d33;color:#b7c6d6;padding:38px 0}@media(max-width:980px){.grid{grid-template-columns:1fr 1fr}.article{grid-template-columns:1fr}.side{position:static}.links a:not(.btn){display:none}}@media(max-width:620px){.grid{grid-template-columns:1fr}.w{width:min(100% - 24px,1120px)}h1{font-size:2.55rem}}`;
function H(){return `<div class="top"><div class="w">Independent New York HUT guidance</div></div><header><nav class="w"><a class="brand" href="/">NewYorkHUT.com</a><div class="links"><a href="/permit-types">Permit Types</a><a href="/university">University</a><a href="/industries">Industries</a><a href="/tools">Tools</a><a href="/resources">Resources</a><a class="btn" href="${ORDER}">Start Permit</a></div></nav></header>`}
function F(){return `<footer><div class="w"><strong>NewYorkHUT.com</strong><p>Private guidance and permit assistance. Not affiliated with New York State.</p></div></footer>`}
function L(t,d,p,b,s=""){return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${t}</title><meta name="description" content="${d}"><meta name="robots" content="index,follow"><link rel="canonical" href="https://newyorkhut.com${p}"><meta property="og:title" content="${t}"><meta property="og:description" content="${d}"><style>${C}</style>${s}</head><body>${H()}${b}${F()}</body></html>`}
function permitHub(){const cards=Object.entries(PERMITS).map(([s,v])=>`<article class="card"><h2>${v[0]}</h2><p>${v[1]}</p><a href="/permit-types/${s}">Review workflow →</a></article>`).join("");return L("New York HUT Permit Types","Compare permanent HUT registration, trip certificates, AFC registration, replacement credentials, added vehicles, account updates, and renewal workflows.","/permit-types",`<main><section class="hero"><div class="w"><div class="crumb"><a href="/">Home</a> / Permit Types</div><div class="eye">Credential authority center</div><h1>Choose the correct New York HUT credential workflow</h1><p class="lead">The correct path depends on trip frequency, cargo, account status, vehicle identity, and whether the carrier is registering, replacing, updating, or renewing.</p></div></section><section><div class="w"><div class="note"><strong>Vehicle-specific control:</strong> a carrier account does not automatically authorize every vehicle. Match each credential to the correct VIN and operating facts.</div><div class="grid">${cards}</div></div></section></main>`,`<script type="application/ld+json">${JSON.stringify({"@context":"https://schema.org","@type":"CollectionPage","name":"New York HUT Permit Types","url":"https://newyorkhut.com/permit-types"})}</script>`)}
function permitPage(s){const v=PERMITS[s],p=`/permit-types/${s}`,rel=Object.entries(PERMITS).filter(([x])=>x!==s).slice(0,6).map(([x,y])=>`<a href="/permit-types/${x}">${y[0]}</a>`).join("");return L(`${v[0]} — New York HUT`,`${v[1]} Review eligibility, required information, records, and next steps.`,p,`<main><section class="hero"><div class="w"><div class="crumb"><a href="/">Home</a> / <a href="/permit-types">Permit Types</a> / ${v[0]}</div><div class="eye">Permit workflow guide</div><h1>${v[0]}</h1><p class="lead">${v[1]}</p></div></section><section><div class="w article"><article><h2>When this workflow applies</h2><p>${v[2]}</p><h2>Information to confirm</h2><ul><li>Carrier legal name, taxpayer identity, and account status</li><li>Vehicle VIN, plate, jurisdiction, year, make, unit number, and ownership</li><li>Truck, tractor, trailer, or specialized-equipment classification</li><li>Gross or unloaded weight and intended New York operation</li><li>Trip frequency, cargo type, and any possible exemption</li></ul><div class="note"><strong>Do not reuse credentials by assumption.</strong> Account, vehicle, decal, certificate, and renewal records must remain synchronized.</div><div class="cta"><h2>Continue to the correct workflow</h2><a class="btn" href="/tools/service-finder">Service Finder</a> <a class="btn" href="${ORDER}">Start Permit</a></div></article><aside class="side"><h3>Other permit types</h3>${rel}<h3>Related guidance</h3><a href="/resources/registration-checklist">Registration checklist</a><a href="/resources/decal-handling-guide">Decal handling</a><a href="/cost">Costs and filing</a></aside></div></section></main>`,`<script type="application/ld+json">${JSON.stringify({"@context":"https://schema.org","@type":"Article","headline":v[0],"mainEntityOfPage":`https://newyorkhut.com${p}`})}</script>`)}
function universityHub(){const cards=Object.entries(COURSES).map(([s,v])=>`<article class="card"><h2>${v[0]}</h2><p>${v[1]}</p><a href="/university/${s}">Start course →</a></article>`).join("");return L("Compliance University — New York HUT Training","Structured New York HUT training covering foundations, vehicle and weight analysis, permits, mileage records, returns, and audit readiness.","/university",`<main><section class="hero"><div class="w"><div class="crumb"><a href="/">Home</a> / Compliance University</div><div class="eye">Compliance University™</div><h1>Learn New York HUT as an operating system—not a collection of forms</h1><p class="lead">Each course converts complex rules into a repeatable workflow for carriers, permit staff, fleet managers, accountants, and compliance teams.</p></div></section><section><div class="w grid">${cards}</div></section></main>`,`<script type="application/ld+json">${JSON.stringify({"@context":"https://schema.org","@type":"CollectionPage","name":"Compliance University","url":"https://newyorkhut.com/university"})}</script>`)}
function coursePage(s){const v=COURSES[s],p=`/university/${s}`,lessons=v[2].map((x,i)=>`<div class="lesson"><strong>Lesson ${i+1}</strong><h2>${x}</h2><p>Use the linked authority centers and operational checklists to apply this lesson to a real carrier, vehicle, trip, or filing period.</p></div>`).join(""),rel=Object.entries(COURSES).filter(([x])=>x!==s).map(([x,y])=>`<a href="/university/${x}">${y[0]}</a>`).join("");const schema={"@context":"https://schema.org","@type":"Course","name":v[0],"description":v[1],"provider":{"@type":"Organization","name":"NewYorkHUT.com","sameAs":"https://newyorkhut.com"}};return L(`${v[0]} — Compliance University`,v[1],p,`<main><section class="hero"><div class="w"><div class="crumb"><a href="/">Home</a> / <a href="/university">University</a> / ${v[0]}</div><div class="eye">Compliance University course</div><h1>${v[0]}</h1><p class="lead">${v[1]}</p></div></section><section><div class="w article"><article>${lessons}<div class="note"><strong>Course objective:</strong> document the reasoning and source records behind every compliance decision rather than relying on memory or fleet-wide assumptions.</div><div class="cta"><h2>Apply the training</h2><a class="btn" href="/tools/eligibility-wizard">Use Eligibility Wizard</a> <a class="btn" href="/resources">Open Checklists</a></div></article><aside class="side"><h3>Other courses</h3>${rel}<h3>Authority centers</h3><a href="/permit-types">Permit types</a><a href="/weight-guide">Weight guide</a><a href="/exemptions">Exemptions</a></aside></div></section></main>`,`<script type="application/ld+json">${JSON.stringify(schema)}</script>`)}
function sitemapPermit(){const u=["/permit-types",...Object.keys(PERMITS).map(x=>`/permit-types/${x}`)];return `<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${u.map(x=>`<url><loc>https://newyorkhut.com${x}</loc><changefreq>monthly</changefreq></url>`).join("")}</urlset>`}
function sitemapUniversity(){const u=["/university",...Object.keys(COURSES).map(x=>`/university/${x}`)];return `<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${u.map(x=>`<url><loc>https://newyorkhut.com${x}</loc><changefreq>monthly</changefreq></url>`).join("")}</urlset>`}
const HH={"content-type":"text/html; charset=UTF-8","cache-control":"public, max-age=300"};
export default{async fetch(r,e,c){const p=new URL(r.url).pathname.replace(/\/+$/g,"")||"/";if(p==="/permit-types")return new Response(permitHub(),{headers:HH});if(p.startsWith("/permit-types/")){const s=p.split("/").pop();if(PERMITS[s])return new Response(permitPage(s),{headers:HH});}if(p==="/university")return new Response(universityHub(),{headers:HH});if(p.startsWith("/university/")){const s=p.split("/").pop();if(COURSES[s])return new Response(coursePage(s),{headers:HH});}if(p==="/sitemap-permit-types.xml")return new Response(sitemapPermit(),{headers:{"content-type":"application/xml; charset=UTF-8"}});if(p==="/sitemap-university.xml")return new Response(sitemapUniversity(),{headers:{"content-type":"application/xml; charset=UTF-8"}});return site.fetch(r,e,c)}};