import site from "./index-v37.js";
import {HUT_KNOWLEDGE_BASE,answerHutQuestion} from "./hut-knowledge-base-v1.js";

const VERSION="v38",ORDER="https://nyhut.com/";
const HTML={"content-type":"text/html; charset=UTF-8","cache-control":"no-store"};
const JSON_HEADERS={"content-type":"application/json; charset=UTF-8","cache-control":"no-store"};
const esc=v=>String(v??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]));

function shell(title,description,body){return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)}</title><meta name="description" content="${esc(description)}"><style>
:root{--n:#082b4c;--b:#1768c5;--l:#dbe5ef;--m:#5b6b7e;--bg:#f5f9fc;--ok:#147a52;--warn:#f4b83f;font-family:Inter,system-ui,sans-serif}*{box-sizing:border-box}body{margin:0;color:#122033;line-height:1.55}.w{width:min(1280px,calc(100% - 40px));margin:auto}.top{background:var(--n);color:white;padding:8px 0;font-size:.9rem}header{border-bottom:1px solid var(--l);background:#fff;position:sticky;top:0;z-index:10}nav{min-height:72px;display:flex;align-items:center;justify-content:space-between;gap:18px}.brand{font-weight:900;color:var(--n);text-decoration:none}.links{display:flex;gap:18px;align-items:center}.links a{color:var(--n);text-decoration:none;font-weight:800}.btn{display:inline-flex;align-items:center;justify-content:center;border:0;border-radius:11px;background:var(--b);color:#fff!important;text-decoration:none;font-weight:850;padding:13px 18px;cursor:pointer;font:inherit}.btn.alt{background:white;color:var(--b)!important;border:1px solid var(--b)}.hero{padding:50px 0 34px;background:linear-gradient(#f9fcff,#edf5fb)}h1{font-size:clamp(2.35rem,5vw,4.2rem);line-height:1;letter-spacing:-.04em;color:var(--n);margin:10px 0 16px}.lead{font-size:1.13rem;color:#4e6074;max-width:900px}.app{padding:38px 0 70px}.panel{border:1px solid var(--l);border-radius:20px;padding:28px;background:#fff;box-shadow:0 10px 34px rgba(8,43,76,.06)}label{display:block;font-weight:850;color:var(--n);margin-bottom:8px}textarea,input{width:100%;border:1px solid #b9c9d8;border-radius:12px;padding:15px 16px;font:inherit}textarea{min-height:120px;resize:vertical}.actions{display:flex;gap:12px;flex-wrap:wrap;margin-top:16px}.chips{display:flex;gap:9px;flex-wrap:wrap;margin:16px 0 0}.chip{border:1px solid var(--l);background:var(--bg);color:var(--n);padding:8px 11px;border-radius:999px;font-weight:750;cursor:pointer}.answer{display:none;margin-top:24px}.answer.show{display:block}.answer-card{border:1px solid var(--l);border-radius:20px;padding:28px;background:#fff}.answer-card h2{color:var(--n);margin:0 0 12px}.confidence{display:inline-flex;padding:5px 9px;border-radius:999px;background:#e7f6ef;color:var(--ok);font-size:.8rem;font-weight:850}.follow{margin-top:18px;padding:16px 18px;background:#fff8e5;border-left:4px solid var(--warn)}.source-list{margin-top:18px;padding-top:16px;border-top:1px solid var(--l)}.source-list a{color:var(--b)}.search-grid{display:grid;gap:14px;margin-top:22px}.result{border:1px solid var(--l);border-radius:15px;padding:20px;background:#fff}.result h3{margin:0 0 7px;color:var(--n)}.result p{margin:0 0 12px;color:var(--m)}.muted{color:var(--m)}footer{background:#071d33;color:#b7c6d6;padding:38px 0}@media(max-width:760px){.w{width:min(100% - 24px,1280px)}.links a:not(.btn){display:none}.panel,.answer-card{padding:20px}}
</style></head><body><div class="top"><div class="w">Independent New York HUT guidance</div></div><header><nav class="w"><a class="brand" href="/">NewYorkHUT.com</a><div class="links"><a href="/tools">Tools</a><a href="/search">Search</a><a href="/tools/compliance-assistant">Assistant</a><a class="btn" href="${ORDER}">Start Permit</a></div></nav></header>${body}<footer><div class="w"><strong>NewYorkHUT.com</strong><p>Private educational guidance and permit assistance. Not affiliated with New York State.</p></div></footer></body></html>`}

function assistantPage(){const prompts=["How long is a HUT permit good for?","Do I need HUT?","When is MT-903 due?","What is a trip certificate?","What records must I keep?"];return shell("New York HUT Compliance Assistant","Ask practical New York HUT questions and receive answers from a curated regulatory knowledge base.",`<main><section class="hero"><div class="w"><div class="muted"><a href="/tools">Tools</a> / Compliance Assistant</div><h1>New York HUT Compliance Assistant</h1><p class="lead">Ask a practical question. Answers are matched against a curated HUT knowledge base and include official New York source links.</p></div></section><section class="app"><div class="w"><div class="panel"><form id="f"><label for="q">Your question</label><textarea id="q" required placeholder="Example: How long is the permit good for?"></textarea><div class="actions"><button class="btn" type="submit">Get Guidance</button><button class="btn alt" type="button" id="clear">Clear</button></div><div class="chips">${prompts.map(p=>`<button type="button" class="chip">${esc(p)}</button>`).join("")}</div></form></div><div id="answer" class="answer"></div></div></section></main><script>
const f=document.getElementById('f'),q=document.getElementById('q'),box=document.getElementById('answer');const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function render(d){const actions=(d.actions||[]).map(a=>'<a class="btn" href="'+esc(a.href)+'">'+esc(a.label)+'</a>').join('');const sources=(d.sources||[]).map(s=>'<li><a target="_blank" rel="noopener" href="'+esc(s.href)+'">'+esc(s.label)+'</a></li>').join('');box.className='answer show';box.innerHTML='<div class="answer-card"><span class="confidence">'+esc((d.confidence||'grounded')+' match')+'</span><h2>'+esc(d.title||'Guidance')+'</h2><p>'+esc(d.answer||d.error)+'</p>'+(d.followUp?'<div class="follow"><strong>Helpful follow-up:</strong><br>'+esc(d.followUp)+'</div>':'')+(actions?'<div class="actions">'+actions+'</div>':'')+(sources?'<div class="source-list"><strong>Official sources</strong><ul>'+sources+'</ul></div>':'')+'</div>'}
f.addEventListener('submit',async e=>{e.preventDefault();box.className='answer show';box.innerHTML='<div class="answer-card">Searching the HUT knowledge base…</div>';const r=await fetch('/api/hut-answer?q='+encodeURIComponent(q.value));render(await r.json())});document.querySelectorAll('.chip').forEach(b=>b.onclick=()=>{q.value=b.textContent;f.requestSubmit()});document.getElementById('clear').onclick=()=>{q.value='';box.className='answer';box.innerHTML='';q.focus()};
</script>`)}

function searchPage(){return shell("Search New York HUT Guidance","Search the NewYorkHUT.com knowledge base for permits, filing, records, exemptions, credentials, and enforcement.",`<main><section class="hero"><div class="w"><h1>Search New York HUT Guidance</h1><p class="lead">Search permits, filing, trip certificates, vehicle eligibility, records, exemptions, credentials, and enforcement topics.</p></div></section><section class="app"><div class="w"><div class="panel"><label for="s">Search the knowledge base</label><div class="actions" style="margin-top:0"><input id="s" placeholder="Try: trip permit, MT-903, decal, exemption" style="flex:1;min-width:240px"><button id="go" class="btn">Search</button></div></div><div id="results" class="search-grid"></div></div></section></main><script>
const s=document.getElementById('s'),r=document.getElementById('results');const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));async function go(){const x=s.value.trim();if(!x){r.innerHTML='';return}r.innerHTML='<div class="result">Searching…</div>';const d=await (await fetch('/api/search?q='+encodeURIComponent(x))).json();r.innerHTML=d.results.length?d.results.map(i=>'<article class="result"><h3>'+esc(i.title)+'</h3><p>'+esc(i.answer)+'</p><div class="actions"><a class="btn alt" href="/tools/compliance-assistant?q='+encodeURIComponent(i.title)+'">Ask Assistant</a></div></article>').join(''):'<div class="result"><h3>No strong match</h3><p>Try permit, trip certificate, filing, MT-903, records, decal, exemption, suspension, or vehicle weight.</p></div>'}document.getElementById('go').onclick=go;s.addEventListener('keydown',e=>{if(e.key==='Enter')go()});
</script>`)}

function searchKnowledge(q){const text=String(q||"").toLowerCase().trim();if(!text)return[];const words=text.split(/\s+/).filter(Boolean);return HUT_KNOWLEDGE_BASE.map(item=>{const hay=[item.title,item.answer,...item.keywords].join(" ").toLowerCase();let score=0;for(const w of words)if(hay.includes(w))score+=w.length>3?3:1;for(const k of item.keywords)if(text.includes(k.toLowerCase()))score+=6;return{...item,score}}).filter(x=>x.score>0).sort((a,b)=>b.score-a.score).slice(0,8)}

export default{async fetch(request,env,ctx){const u=new URL(request.url),p=u.pathname.replace(/\/+$/g,"")||"/";if(p==="/tools/compliance-assistant")return new Response(assistantPage(),{headers:HTML});if(p==="/search")return new Response(searchPage(),{headers:HTML});if(p==="/api/hut-answer")return new Response(JSON.stringify(answerHutQuestion(u.searchParams.get("q"))),{headers:JSON_HEADERS});if(p==="/api/search")return new Response(JSON.stringify({query:u.searchParams.get("q")||"",results:searchKnowledge(u.searchParams.get("q"))}),{headers:JSON_HEADERS});if(p==="/__version"||p==="/api/version")return new Response(JSON.stringify({application:"NewYorkHUT.com",version:VERSION,deployedAt:"2026-07-21",knowledgeBaseEntries:HUT_KNOWLEDGE_BASE.length,features:["/tools/compliance-assistant","/search","/api/hut-answer","/api/search"]},null,2),{headers:{...JSON_HEADERS,"x-newyorkhut-version":VERSION}});const response=await site.fetch(request,env,ctx),headers=new Headers(response.headers);headers.set("x-newyorkhut-version",VERSION);return new Response(response.body,{status:response.status,statusText:response.statusText,headers})}};
