import site from './index-v60.js';

const VERSION='v61';
const ORDER='https://www.nyhut.com/';
const ASK='/ask-hut-ai';
const CERT='https://www.tax.ny.gov/pubs_and_bulls/tg_bulletins/hut/certificate_of_registration.htm';
const DECALS='https://www.tax.ny.gov/pubs_and_bulls/tg_bulletins/hut/decals.htm';
const TMT1='https://www.tax.ny.gov/pdf/current_forms/motor/tmt1.pdf';

const CSS=`<style id="nyh-v61-registration-css">
:root{--n:#082b4c;--b:#1768c5;--l:#d7e3ed;--m:#5b6f83;--p:#f3f8fc;--y:#fff8df;font-family:Inter,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}*{box-sizing:border-box}body{margin:0;color:#13263a;line-height:1.58}.w{width:min(1160px,calc(100% - 40px));margin:auto}header{position:sticky;top:0;z-index:9999;background:#fff;border-bottom:1px solid var(--l);box-shadow:0 4px 18px rgba(8,43,76,.06)}.nav{min-height:76px;display:flex;align-items:center;justify-content:space-between;gap:18px}.brand{font-weight:950;color:var(--n);text-decoration:none;font-size:1.15rem}.links{display:flex;gap:8px;flex-wrap:wrap}.links a{padding:9px 13px;border:1px solid #b8cad9;border-radius:10px;text-decoration:none;color:var(--n);font-weight:850}.links .order{background:var(--b);color:#fff;border-color:var(--b)}.hero{padding:58px 0 44px;background:linear-gradient(135deg,#f9fcff,#eaf4fc)}h1{font-size:clamp(2.3rem,5vw,4rem);line-height:1.03;letter-spacing:-.04em;color:var(--n);margin:10px 0 16px}h2,h3{color:var(--n)}.lead{max-width:930px;color:#496078;font-size:1.08rem}.eyebrow{font-size:.76rem;text-transform:uppercase;letter-spacing:.09em;font-weight:900;color:var(--b)}.section{padding:48px 0 72px}.grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:20px}.card,.panel{border:1px solid var(--l);border-radius:20px;padding:24px;background:#fff;box-shadow:0 10px 34px rgba(8,43,76,.06)}.card p,.card li{color:var(--m)}.btn{display:inline-flex;align-items:center;justify-content:center;margin:10px 8px 0 0;padding:12px 16px;border-radius:10px;background:var(--b);color:#fff;text-decoration:none;font-weight:900}.secondary{background:#fff;color:var(--b);border:1px solid var(--b)}.notice{background:var(--y);border-left:4px solid #e2a500;padding:16px;border-radius:8px;margin:20px 0}.steps{padding-left:22px}.steps li{margin:10px 0}.related{display:flex;gap:10px;flex-wrap:wrap;margin-top:20px}.related a{padding:9px 12px;border:1px solid var(--l);border-radius:999px;text-decoration:none;color:var(--n);font-weight:800}.source{background:var(--p);border:1px solid #cfe0ee;border-radius:18px;padding:22px;margin-top:24px}.faq details{border-bottom:1px solid var(--l);padding:14px 0}.faq summary{font-weight:850;color:var(--n);cursor:pointer}@media(max-width:800px){.grid{grid-template-columns:1fr}.nav{display:block;padding:12px 0}.brand{display:block;margin-bottom:10px}.links{display:grid;grid-template-columns:repeat(2,1fr)}.links a{text-align:center}.links .order{grid-column:1/-1}.w{width:min(100% - 24px,1160px)}}
</style>`;

function header(){return `<header><div class="w nav"><a class="brand" href="/">NewYorkHUT.com</a><nav class="links" aria-label="Primary navigation"><a href="/learn">Learn</a><a href="/hut-registration-center">Registration</a><a href="/mt-903-filing-center">MT-903 Filing</a><a href="/vehicle-lifecycle">Vehicle Changes</a><a href="/tools">Tools</a><a href="${ASK}">Ask HUT AI</a><a class="order" href="${ORDER}">Go to NYHUT</a></nav></div></header>`}
function shell(title,description,path,body){return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${title}</title><meta name="description" content="${description}"><link rel="canonical" href="https://newyorkhut.com${path}">${CSS}</head><body>${header()}${body}</body></html>`}
function related(){return `<div class="related"><a href="/hut-registration-center">Registration Center</a><a href="/tools/hut-permit-requirement">Permit Wizard</a><a href="/tools/hut-rate-lookup">Rate Lookup</a><a href="/tools/hut-tax-estimator">Tax Estimator</a><a href="${ASK}">Ask HUT AI</a><a href="${ORDER}">Open NYHUT</a></div>`}

const pages={
'/learn/who-needs-a-new-york-hut-permit':{title:'Who Needs a New York HUT Permit?',desc:'Learn which trucks and tractors generally need a New York Highway Use Tax certificate.',quick:'A truck, tractor, or other qualifying motor vehicle operating on New York public highways generally needs HUT registration when it exceeds the applicable weight threshold and no specific exclusion or exemption applies.',steps:['Confirm the vehicle will operate on New York public highways.','Determine the registered gross weight or applicable unloaded weight.','Review whether the vehicle is excluded or exempt.','Confirm whether a HUT or automotive fuel carrier credential is required.','Register before taxable New York operation.'],mistakes:['Assuming interstate registration replaces HUT.','Using actual trip weight instead of the registered HUT weight.','Relying on an exemption without documentation.'],source:CERT},
'/learn/how-to-register-for-new-york-hut':{title:'How to Register for New York HUT',desc:'Step-by-step overview of New York HUT registration through OSCAR, Form TMT-1, or a permit service.',quick:'Register the carrier account and each qualifying vehicle using accurate legal name, address, VIN, plate, and registered weight information. New York allows registration through OSCAR, Form TMT-1, or an approved service provider.',steps:['Gather legal business and taxpayer information.','Collect VIN, plate, ownership, vehicle type, and registered weight for each unit.','Choose OSCAR, Form TMT-1, or a permit service.','Submit the application and applicable fees.','Review the issued certificate and decal for accuracy.','Add the vehicle to mileage and MT-903 filing records.'],mistakes:['Submitting a VIN or plate mismatch.','Registering at the wrong gross weight.','Failing to prepare for quarterly filing after registration.'],source:TMT1},
'/learn/new-york-hut-certificate-of-registration':{title:'New York HUT Certificate of Registration Explained',desc:'Understand what the HUT certificate proves, what information it contains, and why it is vehicle-specific.',quick:'The HUT certificate identifies the carrier and vehicle authorized for HUT operation. It is vehicle-specific and should match the VIN, plate, and registered weight shown in the carrier’s records.',steps:['Verify the certificate number and carrier name.','Confirm VIN and plate details.','Confirm the registered gross weight or filing method.','Keep the certificate available as required.','Request correction or replacement when information is wrong or the document is lost.'],mistakes:['Using one certificate for multiple trucks.','Ignoring incorrect VIN or plate data.','Assuming the certificate transfers with a sold vehicle.'],source:CERT},
'/learn/new-york-hut-decals-explained':{title:'New York HUT Decals Explained',desc:'Learn how HUT decals are assigned, displayed, replaced, and surrendered.',quick:'A HUT decal is tied to a specific vehicle and credential. It cannot be transferred to another truck or to a buyer, and it must be replaced or surrendered when required.',steps:['Confirm the decal matches the correct vehicle.','Affix it in the required location.','Do not move it between vehicles.','Request replacement if lost, damaged, or unreadable.','Remove and surrender it when the vehicle leaves the carrier’s control.'],mistakes:['Leaving the decal on a sold truck.','Borrowing a decal from another vehicle.','Creating an unofficial replacement.'],source:DECALS},
'/learn/temporary-hut-permits-and-first-trip-questions':{title:'Temporary HUT Permits and First-Trip Questions',desc:'What to know before a newly acquired or newly registered truck makes its first New York trip.',quick:'Do not assume a truck may operate in New York while a permanent HUT credential is pending. Confirm whether a temporary credential is available and valid for the exact vehicle and trip before operation.',steps:['Confirm the vehicle is subject to HUT.','Verify whether a temporary credential is available for the situation.','Check the VIN, plate, and effective dates.','Carry the required proof during the trip.','Complete permanent registration and filing setup promptly.'],mistakes:['Treating an application receipt as operating authority.','Using another vehicle’s temporary credential.','Ignoring the first MT-903 filing period.'],source:CERT},
'/learn/how-gvw-affects-your-hut-tax':{title:'How GVW Affects New York HUT Tax',desc:'Understand how registered gross vehicle weight affects HUT rates and tax estimates.',quick:'Under the gross-weight method, the per-mile HUT rate increases by registered gross vehicle weight bracket. A weight change can therefore change both the credential information and the tax due.',steps:['Identify the registered gross weight shown on the credential.','Look up the applicable MT-903 rate bracket.','Use taxable New York mileage for the filing period.','Update the credential before relying on a new weight.','Retain records supporting any weight change.'],mistakes:['Confusing GVWR with registered gross weight.','Using a new rate before the credential is updated.','Applying laden rates to mileage that belongs in another category.'],source:CERT},
'/learn/common-hut-registration-mistakes':{title:'Common New York HUT Registration Mistakes',desc:'Avoid the most frequent HUT registration errors involving names, VINs, plates, weights, decals, and filing setup.',quick:'Most registration problems come from inaccurate vehicle data, misunderstood weight rules, transferable-credential assumptions, or failure to prepare for ongoing MT-903 filing.',steps:['Match the legal name and taxpayer records.','Verify every VIN character.','Use the correct plate and jurisdiction.','Confirm registered weight before submission.','Check the issued certificate and decal immediately.','Set up mileage records and filing reminders.'],mistakes:['Registering the wrong entity.','Entering a temporary or outdated plate.','Assuming registration is the only ongoing obligation.'],source:TMT1}
};

function guide(path,data){const body=`<main><section class="hero"><div class="w"><div class="eyebrow">New York HUT registration guide</div><h1>${data.title}</h1><p class="lead">${data.quick}</p></div></section><section class="section"><div class="w"><div class="grid"><article class="card"><h2>Quick answer</h2><p>${data.quick}</p><h2>Step-by-step</h2><ol class="steps">${data.steps.map(x=>`<li>${x}</li>`).join('')}</ol></article><article class="card"><h2>Common mistakes</h2><ul>${data.mistakes.map(x=>`<li>${x}</li>`).join('')}</ul><div class="notice"><strong>Important:</strong> Verify current New York requirements and make sure the issued credential matches the actual vehicle before operation.</div><a class="btn" href="${ORDER}">Start or manage registration in NYHUT →</a><a class="btn secondary" href="${ASK}">Ask HUT AI →</a></article></div><div class="source"><h2>Official reference</h2><p>This guide is based on current New York Tax Department HUT registration and credential guidance.</p><a class="btn" href="${data.source}" target="_blank" rel="noopener">View official guidance →</a>${related()}</div></div></section></main>`;return shell(`${data.title} | NewYorkHUT.com`,data.desc,path,body)}

function hub(){const cards=[
['Who Needs HUT?','/learn/who-needs-a-new-york-hut-permit','Determine whether a truck or tractor generally requires HUT registration.'],
['How to Register','/learn/how-to-register-for-new-york-hut','Prepare the carrier and vehicle information needed to register.'],
['Certificate Explained','/learn/new-york-hut-certificate-of-registration','Understand the certificate, vehicle-specific data, and corrections.'],
['HUT Decals','/learn/new-york-hut-decals-explained','Display, replace, and surrender vehicle decals correctly.'],
['Temporary Permits and First Trip','/learn/temporary-hut-permits-and-first-trip-questions','Confirm authority before a newly acquired truck enters New York.'],
['How GVW Affects Tax','/learn/how-gvw-affects-your-hut-tax','See how registered weight affects HUT rate brackets.'],
['Common Registration Mistakes','/learn/common-hut-registration-mistakes','Avoid errors involving entity names, VINs, plates, weights, and filing setup.']
];const body=`<main><section class="hero"><div class="w"><div class="eyebrow">New York HUT registration guidance</div><h1>HUT Registration Center</h1><p class="lead">Use this center to determine whether HUT applies, prepare a registration, understand certificates and decals, confirm first-trip authority, and avoid common errors.</p></div></section><section class="section"><div class="w"><div class="grid">${cards.map(c=>`<article class="card"><h2>${c[0]}</h2><p>${c[2]}</p><a class="btn" href="${c[1]}">Open guide →</a></article>`).join('')}</div><div class="source"><h2>From research to registration</h2><p>Use the free guides and tools here, then complete the permit workflow in NYHUT.</p><a class="btn" href="/tools/hut-permit-requirement">Use Permit Wizard →</a><a class="btn secondary" href="${ORDER}">Start HUT registration →</a>${related()}</div></div></section></main>`;return shell('New York HUT Registration Center','Guides for HUT permit requirements, registration, certificates, decals, temporary operation, GVW, and common mistakes.','/hut-registration-center',body)}

function injectLinks(html){if(html.includes('HUT Registration Center'))return html;const block=`<section class="panel" style="margin:24px auto;width:min(1100px,calc(100% - 40px))"><h2>HUT registration guidance</h2><p>Review permit requirements, registration steps, certificates, decals, temporary operation, and GVW rules.</p><a class="btn" href="/hut-registration-center">Open HUT Registration Center →</a></section>`;let out=html;if(!out.includes('nyh-v61-registration-css'))out=out.replace(/<\/head>/i,`${CSS}</head>`);return out.replace(/<\/main>/i,`${block}</main>`)}

export default{async fetch(request,env,ctx){const url=new URL(request.url);const path=url.pathname.replace(/\/+$/,'')||'/';if(path==='/hut-registration-center'||path==='/registration-center')return new Response(hub(),{headers:{'content-type':'text/html; charset=utf-8','cache-control':'no-store','x-newyorkhut-version':VERSION,'x-newyorkhut-feature':'hut-registration-center-v61'}});if(pages[path])return new Response(guide(path,pages[path]),{headers:{'content-type':'text/html; charset=utf-8','cache-control':'no-store','x-newyorkhut-version':VERSION,'x-newyorkhut-feature':'hut-registration-guides-v61'}});const response=await site.fetch(request,env,ctx);if((path==='/learn'||path==='/ask-hut-ai'||path==='/services')&&(response.headers.get('content-type')||'').includes('text/html')){const headers=new Headers(response.headers);headers.set('cache-control','no-store');headers.set('x-newyorkhut-version',VERSION);return new Response(injectLinks(await response.text()),{status:response.status,headers})}return response}};