import base from './index-v43.js';
import {HUT_KNOWLEDGE_BASE} from './hut-knowledge-base-v2.js';

const VERSION='v45';
const ORDER='https://nyhut.com/';
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const J=(data,status=200)=>new Response(JSON.stringify(data,null,2),{status,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store'}});
const STATIC=[
 ['Tool','Truck VIN Decoder','Decode vehicle information and review preliminary compliance guidance.','/tools/vin-decoder','vin truck vehicle decoder'],
 ['Tool','Fleet Compliance Dashboard','Assess fleet readiness and missing compliance controls.','/tools/fleet-compliance','fleet compliance audit'],
 ['Tool','Compliance Calendar','Build HUT, IFTA, IRP, UCR, and filing dates.','/tools/compliance-calendar','calendar due date filing mt-903'],
 ['Tool','Compliance Assistant','Ask a HUT question or run a guided requirement check.','/tools/compliance-assistant','assistant eligibility question'],
 ['Resource','Fleet Compliance Toolkit','Download fleet inventory, mileage, fuel, and audit templates.','/fleet-toolkit','template download mileage fuel'],
 ['Resource','Official New York Resources','Open state forms, bulletins, and filing resources.','/official-resources','official form bulletin tax department'],
 ['Resource','HUT FAQ Library','Browse detailed answers to common HUT questions.','/new-york-hut','faq knowledge answers']
].map(x=>({type:x[0],title:x[1],description:x[2],href:x[3],keywords:x[4]}));
const HUBS={
 permits:{title:'New York HUT Permits and Credentials',description:'Regular credentials, trip certificates, costs, processing, and permit selection.',slugs:['do-i-need-new-york-hut','do-out-of-state-trucks-need-hut','how-much-does-a-new-york-hut-permit-cost','how-long-is-a-new-york-hut-permit-valid','what-is-a-new-york-hut-trip-certificate','how-many-new-york-hut-trip-permits-can-i-get','how-fast-can-i-get-a-new-york-hut-credential','how-do-i-open-a-new-york-hut-account']},
 'filing-and-taxes':{title:'New York HUT Filing and Taxes',description:'MT-903 deadlines, zero-mile returns, mileage records, Thruway treatment, and account closure.',slugs:['when-is-form-mt-903-due','do-i-file-hut-if-i-had-no-new-york-miles','how-do-i-close-a-new-york-hut-account','what-records-must-i-keep-for-new-york-hut','is-new-york-thruway-mileage-subject-to-hut','new-york-hut-vs-ifta']},
 'vehicles-and-decals':{title:'HUT Vehicles, Decals, and Fleet Changes',description:'Vehicle additions, removals, decals, plate changes, leased trucks, and credential updates.',slugs:['how-do-i-add-a-vehicle-to-my-hut-account','how-do-i-remove-or-cancel-a-hut-vehicle','what-if-my-hut-decal-is-lost-or-damaged','how-do-i-change-a-license-plate-on-a-hut-credential','who-needs-hut-on-a-leased-truck','new-york-hut-weight-threshold']},
 exemptions:{title:'New York HUT Exemptions and Eligibility',description:'Weight thresholds, exempt vehicles, out-of-state operation, leases, and special-use situations.',slugs:['do-i-need-new-york-hut','new-york-hut-weight-threshold','do-out-of-state-trucks-need-hut','what-vehicles-are-exempt-from-new-york-hut','who-needs-hut-on-a-leased-truck','can-an-automotive-fuel-carrier-use-a-hut-trip-certificate']},
 enforcement:{title:'New York HUT Enforcement and Account Status',description:'Penalties, credential restrictions, filing failures, balances, and corrective actions.',slugs:['what-happens-if-i-do-not-file-or-pay-hut','how-do-i-close-a-new-york-hut-account','do-i-file-hut-if-i-had-no-new-york-miles','when-is-form-mt-903-due']}
};
const CSS=`:root{--n:#082b4c;--b:#1768c5;--l:#dbe5ef;--bg:#f4f8fb;font-family:Inter,system-ui,sans-serif}*{box-sizing:border-box}body{margin:0;color:#132235;line-height:1.55}nav{min-height:72px;border-bottom:1px solid var(--l);display:flex;align-items:center;justify-content:space-between;gap:18px;padding:0 max(20px,calc((100% - 1180px)/2));position:sticky;top:0;background:#fff;z-index:9}nav a{color:var(--n);font-weight:800;text-decoration:none;margin-right:15px}.order,.btn{display:inline-block;background:var(--b);color:#fff!important;padding:12px 17px;border-radius:10px;border:0;text-decoration:none;font-weight:850;cursor:pointer}.w{width:min(1180px,calc(100% - 40px));margin:auto}.hero{padding:56px 0 42px;background:linear-gradient(#fbfdff,#edf5fb)}h1{font-size:clamp(2.4rem,5vw,4.4rem);line-height:1;color:var(--n);letter-spacing:-.04em}h2,h3{color:var(--n)}.lead{font-size:1.15rem;color:#536579;max-width:900px}.section{padding:46px 0 70px}.grid{display:grid;grid-template-columns:repeat(3,1fr);gap:18px}.card,.panel,.result{border:1px solid var(--l);border-radius:16px;padding:22px;background:#fff}.card a,.result{color:var(--b);font-weight:800;text-decoration:none}.tag{font-size:.75rem;text-transform:uppercase;letter-spacing:.08em;font-weight:900;color:var(--b)}.search{display:grid;grid-template-columns:1fr auto;gap:10px}.search input,input,select,textarea{width:100%;padding:14px;border:1px solid #b9c9d8;border-radius:10px;font:inherit}.filters{display:flex;gap:8px;flex-wrap:wrap;margin:16px 0}.filter{border:1px solid var(--l);background:#fff;padding:8px 12px;border-radius:999px;font-weight:750}.active{background:var(--n);color:#fff}.result{display:block;color:inherit;margin:12px 0}.formgrid{display:grid;grid-template-columns:1fr 1fr;gap:15px}.full{grid-column:1/-1}.cta{margin-top:30px;background:var(--n);color:#fff;padding:25px;border-radius:16px}.cta h2{color:#fff}.notice{margin-top:14px;padding:14px;background:var(--bg);border-radius:10px}@media(max-width:800px){.grid{grid-template-columns:1fr 1fr}.formgrid{grid-template-columns:1fr}.full{grid-column:auto}nav .links{display:none}}@media(max-width:560px){.grid,.search{grid-template-columns:1fr}.w{width:min(100% - 24px,1180px)}}`;
const nav=`<nav><a href="/">NewYorkHUT.com</a><div class="links"><a href="/new-york-hut">FAQ Library</a><a href="/new-york-hut/topics">Topics</a><a href="/search">Search</a><a href="/tools/compliance-assistant">Assistant</a><a href="/contact">Get Help</a></div><a class="order" href="${ORDER}" data-track="start-permit">Start Permit</a></nav>`;
function page(title,description,path,body,schema=''){return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)}</title><meta name="description" content="${esc(description)}"><link rel="canonical" href="https://newyorkhut.com${path}"><style>${CSS}</style>${schema}</head><body>${nav}${body}${tracking()}</body></html>`}
function tracking(){return `<script>document.addEventListener('click',function(e){const a=e.target.closest('a');if(!a)return;let v=a.dataset.track||'';if(!v&&a.href.includes('nyhut.com'))v='start-permit';if(!v&&a.pathname==='/tools/compliance-assistant')v='ask-assistant';if(!v&&a.pathname==='/fleet-toolkit')v='download-toolkit';if(!v&&a.pathname==='/contact')v='contact-support';if(v)navigator.sendBeacon('/api/track',new Blob([JSON.stringify({event:v,source:document.title,path:location.pathname})],{type:'application/json'}))})</script>`}
function searchPage(){return page('Search New York HUT Guidance','Search HUT FAQs, compliance tools, official resources, and permit guidance.','/search',`<main><section class="hero"><div class="w"><div class="tag">Authority search</div><h1>Search New York HUT Guidance</h1><p class="lead">Search the knowledge base, compliance tools, official resources, and permit guidance.</p><div class="search"><input id="q" placeholder="Try: trip permit, MT-903, lost decal"><button class="btn" id="go">Search</button></div><div class="filters"><button class="filter active" data-type="All">All</button><button class="filter" data-type="FAQ">FAQ</button><button class="filter" data-type="Tool">Tools</button><button class="filter" data-type="Resource">Resources</button></div></div></section><section class="section"><div class="w"><div id="count"></div><div id="results"></div><div id="empty" class="panel" hidden><h2>No exact match</h2><p>Try fewer words or ask the Compliance Assistant.</p><a class="btn" href="/tools/compliance-assistant">Ask Assistant</a></div></div></section></main><script>let type='All';const q=document.getElementById('q'),r=document.getElementById('results'),c=document.getElementById('count'),z=document.getElementById('empty'),safe=s=>String(s||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));async function run(){const d=await(await fetch('/api/site-search?q='+encodeURIComponent(q.value)+'&type='+encodeURIComponent(type))).json();c.textContent=d.results.length+' result'+(d.results.length===1?'':'s');z.hidden=!!d.results.length;r.innerHTML=d.results.map(x=>'<a class="result" href="'+safe(x.href)+'"><div class="tag">'+safe(x.type)+'</div><h2>'+safe(x.title)+'</h2><p>'+safe(x.description)+'</p></a>').join('')}q.oninput=()=>{clearTimeout(window.t);window.t=setTimeout(run,180)};document.getElementById('go').onclick=run;document.querySelector('.filters').onclick=e=>{const b=e.target.closest('button');if(!b)return;document.querySelectorAll('.filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');type=b.dataset.type;run()};run()</script>`)}
function topicIndex(){const cards=Object.entries(HUBS).map(([s,h])=>`<article class="card"><div class="tag">Topic hub</div><h2>${esc(h.title)}</h2><p>${esc(h.description)}</p><a href="/new-york-hut/${s}">Explore topic →</a></article>`).join('');return page('New York HUT Topic Guides','Grouped HUT permit, filing, vehicle, exemption, and enforcement guidance.','/new-york-hut/topics',`<main><section class="hero"><div class="w"><div class="tag">Authority guides</div><h1>Explore New York HUT by Topic</h1><p class="lead">Move from a broad question to the exact guidance, source, or permit action.</p></div></section><section class="section"><div class="w"><div class="grid">${cards}</div></div></section></main>`)}
function topicPage(slug,h){const items=h.slugs.map(s=>HUT_KNOWLEDGE_BASE.find(x=>x.slug===s)).filter(Boolean);const cards=items.map(x=>`<article class="card"><div class="tag">${esc(x.category)}</div><h2>${esc(x.title)}</h2><p>${esc(x.shortAnswer)}</p><a href="/new-york-hut/${esc(x.slug)}">Read answer →</a></article>`).join('');const schema=`<script type="application/ld+json">${JSON.stringify({'@context':'https://schema.org','@type':'BreadcrumbList',itemListElement:[{'@type':'ListItem',position:1,name:'Home',item:'https://newyorkhut.com/'},{'@type':'ListItem',position:2,name:'HUT Topics',item:'https://newyorkhut.com/new-york-hut/topics'},{'@type':'ListItem',position:3,name:h.title,item:'https://newyorkhut.com/new-york-hut/'+slug}]})}</script>`;return page(h.title,h.description,'/new-york-hut/'+slug,`<main><section class="hero"><div class="w"><p><a href="/new-york-hut/topics">← All topic guides</a></p><div class="tag">Authority topic hub</div><h1>${esc(h.title)}</h1><p class="lead">${esc(h.description)}</p></div></section><section class="section"><div class="w"><div class="grid">${cards}</div><div class="cta"><h2>Ready to obtain or update a credential?</h2><p>Continue to NYHUT.com for ordering and account assistance.</p><a class="btn" href="${ORDER}" data-track="start-permit">Start Permit</a></div></div></section></main>`,schema)}
function contactPage(){return page('New York HUT Help Request','Request help identifying the correct HUT credential or compliance step.','/contact',`<main><section class="hero"><div class="w"><div class="tag">Carrier assistance</div><h1>Need Help Determining What You Need?</h1><p class="lead">Send the carrier and vehicle details you have. We will identify the likely credential or next step.</p></div></section><section class="section"><div class="w"><form id="lead" class="panel"><div class="formgrid"><label>Name<input required name="name"></label><label>Company<input name="company"></label><label>Email<input required type="email" name="email"></label><label>Phone<input name="phone"></label><label>USDOT<input name="usdot"></label><label>Reason<select name="interest"><option>Determine HUT requirement</option><option>New HUT account</option><option>Add or update vehicle</option><option>Trip certificate</option><option>Filing or account issue</option></select></label><label class="full">Question or details<textarea required rows="6" name="question"></textarea></label></div><input type="hidden" name="source_page"><input type="hidden" name="referrer"><button class="btn">Request Assistance</button><div class="notice" id="notice" hidden></div></form></div></section></main><script>const f=document.getElementById('lead'),n=document.getElementById('notice');f.source_page.value=location.pathname;f.referrer.value=document.referrer;f.onsubmit=async e=>{e.preventDefault();n.hidden=false;n.textContent='Submitting…';const d=Object.fromEntries(new FormData(f)),r=await fetch('/api/leads',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(d)}),x=await r.json();n.textContent=r.ok?'Thank you. Your request has been received.':(x.error||'Unable to submit.');if(r.ok)f.reset()}</script>`)}
function search(url){const q=(url.searchParams.get('q')||'').trim().toLowerCase(),type=url.searchParams.get('type')||'All';let rows=HUT_KNOWLEDGE_BASE.map(x=>({type:'FAQ',title:x.title,description:x.shortAnswer,href:'/new-york-hut/'+x.slug,hay:[x.title,x.shortAnswer,x.detail,x.category,...(x.keywords||[])].join(' ').toLowerCase()})).concat(STATIC.map(x=>({...x,hay:[x.title,x.description,x.keywords].join(' ').toLowerCase()})));if(type!=='All')rows=rows.filter(x=>x.type===type);if(q){const words=q.split(/\s+/);rows=rows.map(x=>({...x,score:words.reduce((s,w)=>s+(x.title.toLowerCase().includes(w)?8:0)+(x.hay.includes(w)?2:0),0)})).filter(x=>x.score).sort((a,b)=>b.score-a.score)}return rows.slice(0,30).map(({hay,keywords,...x})=>x)}
async function lead(request,env){let d;try{d=await request.json()}catch{return J({error:'Invalid request.'},400)}const x={name:String(d.name||'').trim().slice(0,120),company:String(d.company||'').trim().slice(0,160),email:String(d.email||'').trim().slice(0,200),phone:String(d.phone||'').trim().slice(0,80),usdot:String(d.usdot||'').replace(/\D/g,'').slice(0,12),interest:String(d.interest||'').slice(0,120),question:String(d.question||'').trim().slice(0,4000),source_page:String(d.source_page||'').slice(0,300),referrer:String(d.referrer||'').slice(0,500),created_at:new Date().toISOString()};if(!x.name||!x.email||!x.question)return J({error:'Name, email, and question are required.'},400);let stored=false,emailed=false;if(env.SUPABASE_URL&&env.SUPABASE_SERVICE_ROLE_KEY){const r=await fetch(env.SUPABASE_URL.replace(/\/$/,'')+'/rest/v1/newyorkhut_leads',{method:'POST',headers:{apikey:env.SUPABASE_SERVICE_ROLE_KEY,authorization:'Bearer '+env.SUPABASE_SERVICE_ROLE_KEY,'content-type':'application/json',prefer:'return=minimal'},body:JSON.stringify(x)});stored=r.ok}if(env.RESEND_API_KEY&&env.LEAD_NOTIFY_EMAIL){const r=await fetch('https://api.resend.com/emails',{method:'POST',headers:{authorization:'Bearer '+env.RESEND_API_KEY,'content-type':'application/json'},body:JSON.stringify({from:env.LEAD_FROM_EMAIL||'NewYorkHUT.com <noreply@newyorkhut.com>',to:[env.LEAD_NOTIFY_EMAIL],reply_to:x.email,subject:'New NewYorkHUT.com assistance request',text:Object.entries(x).map(([k,v])=>k+': '+v).join('\n')})});emailed=r.ok}if(!stored&&!emailed)return J({error:'Lead delivery is not configured yet.'},503);return J({ok:true,stored,emailed})}
async function track(request,env){let d={};try{d=await request.json()}catch{};if(env.SUPABASE_URL&&env.SUPABASE_SERVICE_ROLE_KEY)fetch(env.SUPABASE_URL.replace(/\/$/,'')+'/rest/v1/newyorkhut_events',{method:'POST',headers:{apikey:env.SUPABASE_SERVICE_ROLE_KEY,authorization:'Bearer '+env.SUPABASE_SERVICE_ROLE_KEY,'content-type':'application/json',prefer:'return=minimal'},body:JSON.stringify({event:String(d.event||'unknown').slice(0,80),source:String(d.source||'').slice(0,300),path:String(d.path||'').slice(0,300),created_at:new Date().toISOString()})}).catch(()=>{});return J({ok:true})}
export default{async fetch(request,env,ctx){const u=new URL(request.url),p=u.pathname.replace(/\/+$/,'')||'/';if(p==='/api/version'||p==='/__version')return J({application:'NewYorkHUT.com',version:VERSION,knowledgeBaseEntries:HUT_KNOWLEDGE_BASE.length,features:['authority-search','topic-hubs','breadcrumb-schema','lead-capture','conversion-tracking']});if(p==='/api/site-search')return J({results:search(u)});if(p==='/api/leads'&&request.method==='POST')return lead(request,env);if(p==='/api/track'&&request.method==='POST')return track(request,env);if(p==='/search')return new Response(searchPage(),{headers:{'content-type':'text/html; charset=utf-8'}});if(p==='/new-york-hut/topics')return new Response(topicIndex(),{headers:{'content-type':'text/html; charset=utf-8'}});if(p==='/contact')return new Response(contactPage(),{headers:{'content-type':'text/html; charset=utf-8'}});const m=p.match(/^\/new-york-hut\/(permits|filing-and-taxes|vehicles-and-decals|exemptions|enforcement)$/);if(m)return new Response(topicPage(m[1],HUBS[m[1]]),{headers:{'content-type':'text/html; charset=utf-8'}});const r=await base.fetch(request,env,ctx),h=new Headers(r.headers),t=h.get('content-type')||'';h.set('x-newyorkhut-version',VERSION);if(t.includes('text/html')){let html=await r.text();if(!html.includes('/new-york-hut/topics'))html=html.replace('</body>',`<script>document.addEventListener('click',function(e){const a=e.target.closest('a');if(a&&a.href.includes('nyhut.com'))navigator.sendBeacon('/api/track',new Blob([JSON.stringify({event:'start-permit',source:document.title,path:location.pathname})],{type:'application/json'}))})</script></body>`);return new Response(html,{status:r.status,statusText:r.statusText,headers:h})}return new Response(r.body,{status:r.status,statusText:r.statusText,headers:h})}};
