import site from './index-v45.js';

const VERSION='v47';
const ORDER='https://www.nyhut.com/';
const PORTAL='https://www.nyhut.com/my-nyhut';

const css=`<style id="nyh47-css">
:root{--nyh-navy:#082b4c;--nyh-blue:#1768c5;--nyh-line:#d8e3ed;--nyh-muted:#607286}
body>header:not(#nyh47-header),body>nav:not(.nyh47-menu),body>footer:not(#nyh47-footer){display:none!important}
#nyh47-header{display:block!important;position:sticky;top:0;z-index:2147483000;background:#fff;border-bottom:1px solid var(--nyh-line);box-shadow:0 4px 18px rgba(8,43,76,.08);font-family:Inter,system-ui,sans-serif}
.nyh47-wrap{width:min(1240px,calc(100% - 32px));min-height:76px;margin:auto;display:flex;align-items:center;gap:18px}
.nyh47-brand{display:flex;align-items:center;gap:10px;color:var(--nyh-navy)!important;text-decoration:none!important;font-size:1.18rem;font-weight:950;white-space:nowrap}
.nyh47-mark{display:grid;place-items:center;width:35px;height:35px;border-radius:9px;background:var(--nyh-navy);color:#fff;font-size:.76rem}
.nyh47-menu{display:flex!important;align-items:center;gap:4px;margin-left:auto;min-height:0!important;border:0!important;padding:0!important;position:static!important;background:transparent!important;box-shadow:none!important}
.nyh47-link,.nyh47-trigger{display:flex;align-items:center;gap:5px;padding:11px 9px;border:0;background:transparent;color:var(--nyh-navy)!important;text-decoration:none!important;font:inherit;font-weight:800;cursor:pointer;white-space:nowrap;border-radius:9px;margin:0!important}
.nyh47-link:hover,.nyh47-trigger:hover{background:#eef5fb}
.nyh47-item{position:relative}
.nyh47-drop{display:block;position:absolute;top:calc(100% + 8px);left:0;min-width:285px;padding:10px;background:#fff;border:1px solid var(--nyh-line);border-radius:15px;box-shadow:0 18px 45px rgba(8,43,76,.18);opacity:0;visibility:hidden;transform:translateY(-5px);transition:.15s ease}
.nyh47-item:hover>.nyh47-drop,.nyh47-item:focus-within>.nyh47-drop,.nyh47-item.open>.nyh47-drop{opacity:1;visibility:visible;transform:none}
.nyh47-drop a{display:block!important;padding:10px 12px!important;margin:0!important;border-radius:8px;color:var(--nyh-navy)!important;text-decoration:none!important;font-weight:800}
.nyh47-drop a:hover{background:#eef5fb}
.nyh47-drop small{display:block;color:var(--nyh-muted);font-weight:500;line-height:1.25;margin-top:2px}
.nyh47-portal{border:1px solid #aac4dc!important;padding:10px 12px!important}
.nyh47-order{background:var(--nyh-blue)!important;color:#fff!important;padding:11px 15px!important}
.nyh47-toggle{display:none;margin-left:auto;border:1px solid var(--nyh-line);background:#fff;color:var(--nyh-navy);border-radius:9px;padding:9px 11px;font-size:1.25rem;cursor:pointer}
#nyh47-footer{display:block!important;background:#061f37;color:#dce8f3;padding:52px 0 20px;font-family:Inter,system-ui,sans-serif}
.nyh47-footwrap{width:min(1180px,calc(100% - 40px));margin:auto}.nyh47-grid{display:grid;grid-template-columns:1.25fr repeat(4,1fr);gap:30px}
#nyh47-footer h2,#nyh47-footer h3{color:#fff!important}#nyh47-footer h3{font-size:.82rem;text-transform:uppercase;letter-spacing:.08em}
#nyh47-footer p{color:#b7c9d9}#nyh47-footer a{display:block;color:#dce8f3!important;text-decoration:none!important;margin:8px 0}#nyh47-footer a:hover{text-decoration:underline!important;color:#fff!important}
.nyh47-bottom{border-top:1px solid rgba(255,255,255,.14);margin-top:32px;padding-top:17px;display:flex;justify-content:space-between;gap:16px;color:#9fb3c5;font-size:.87rem}
@media(max-width:1080px){.nyh47-wrap{min-height:70px;flex-wrap:wrap;padding:10px 0}.nyh47-toggle{display:block}.nyh47-menu{display:none!important;order:3;width:100%;margin:0;flex-direction:column;align-items:stretch;padding:7px 0 13px!important}.nyh47-open .nyh47-menu{display:flex!important}.nyh47-link,.nyh47-trigger{width:100%;justify-content:space-between;padding:12px!important}.nyh47-item{width:100%}.nyh47-drop{position:static;display:none;opacity:1;visibility:visible;transform:none;box-shadow:none;border:0;border-left:3px solid var(--nyh-line);border-radius:0;margin-left:12px;padding:3px 8px}.nyh47-item.open>.nyh47-drop{display:block}.nyh47-portal,.nyh47-order{justify-content:center!important}.nyh47-grid{grid-template-columns:repeat(3,1fr)}}
@media(max-width:650px){.nyh47-grid{grid-template-columns:1fr 1fr}.nyh47-grid>div:first-child{grid-column:1/-1}.nyh47-bottom{flex-direction:column}}
@media(max-width:430px){.nyh47-grid{grid-template-columns:1fr}.nyh47-grid>div:first-child{grid-column:auto}}
</style>`;

const header=`<header id="nyh47-header"><div class="nyh47-wrap"><a class="nyh47-brand" href="/"><span class="nyh47-mark">NY</span><span>NewYorkHUT.com</span></a><button class="nyh47-toggle" id="nyh47-toggle" aria-label="Open navigation" aria-expanded="false">☰</button><nav class="nyh47-menu" aria-label="Primary navigation"><a class="nyh47-link" href="/">Home</a><div class="nyh47-item"><button class="nyh47-trigger">Learn <span>⌄</span></button><div class="nyh47-drop"><a href="/what-is-hut">What Is New York HUT?<small>Understand the tax and credential system.</small></a><a href="/new-york-hut/do-i-need-new-york-hut">Do I Need HUT?<small>Review eligibility and weight thresholds.</small></a><a href="/new-york-hut">HUT FAQ Library<small>Browse detailed answers.</small></a><a href="/new-york-hut/topics">Topic Guides<small>Permits, filing, vehicles, and enforcement.</small></a><a href="/official-resources">Official Resources<small>State forms, bulletins, and filing links.</small></a></div></div><div class="nyh47-item"><button class="nyh47-trigger">Tools <span>⌄</span></button><div class="nyh47-drop"><a href="/tools/compliance-assistant">Compliance Assistant</a><a href="/tools/vin-decoder">VIN Decoder</a><a href="/tools/fleet-compliance">Fleet Compliance Check</a><a href="/tools/compliance-calendar">Compliance Calendar</a><a href="/fleet-toolkit">Fleet Toolkit</a><a href="/search">Search Knowledge Center</a></div></div><div class="nyh47-item"><button class="nyh47-trigger">Services <span>⌄</span></button><div class="nyh47-drop"><a href="${ORDER}">New HUT Permit</a><a href="${ORDER}">HUT Trip Certificate</a><a href="${ORDER}">Add or Update a Vehicle</a><a href="/contact">HUT Account Help</a></div></div><a class="nyh47-link" href="/about">About</a><a class="nyh47-link" href="/contact">Contact</a><a class="nyh47-link nyh47-portal" href="${PORTAL}">MY NYHUT</a><a class="nyh47-link nyh47-order" href="${ORDER}">Start Permit</a></nav></div></header>`;

const footer=`<footer id="nyh47-footer"><div class="nyh47-footwrap"><div class="nyh47-grid"><div><h2>NewYorkHUT.com</h2><p>Independent New York Highway Use Tax education, carrier tools, and credential assistance.</p><a href="${ORDER}">Start a HUT Permit</a></div><div><h3>Learn</h3><a href="/what-is-hut">What Is HUT?</a><a href="/new-york-hut/do-i-need-new-york-hut">Do I Need HUT?</a><a href="/new-york-hut">FAQ Library</a><a href="/new-york-hut/topics">Topic Guides</a><a href="/official-resources">Official Resources</a></div><div><h3>Tools</h3><a href="/tools/compliance-assistant">Compliance Assistant</a><a href="/tools/vin-decoder">VIN Decoder</a><a href="/tools/fleet-compliance">Fleet Compliance</a><a href="/tools/compliance-calendar">Compliance Calendar</a><a href="/fleet-toolkit">Fleet Toolkit</a><a href="/search">Site Search</a></div><div><h3>Services</h3><a href="${ORDER}">New HUT Permit</a><a href="${ORDER}">Trip Certificate</a><a href="${ORDER}">Add a Vehicle</a><a href="/contact">Existing Account Help</a></div><div><h3>Customer & Company</h3><a href="${PORTAL}">MY NYHUT</a><a href="${PORTAL}">Order Status</a><a href="${PORTAL}">Customer Dashboard</a><a href="/about">About</a><a href="/contact">Contact</a><a href="/privacy-policy">Privacy Policy</a><a href="/terms">Terms</a></div></div><div class="nyh47-bottom"><span>© ${new Date().getFullYear()} NewYorkHUT.com.</span><span>Independent permit service and educational resource—not a New York State agency.</span></div></div></footer>`;

const js=`<script id="nyh47-js">(()=>{const h=document.getElementById('nyh47-header'),t=document.getElementById('nyh47-toggle');if(t)t.onclick=()=>{const o=h.classList.toggle('nyh47-open');t.setAttribute('aria-expanded',String(o))};document.querySelectorAll('.nyh47-trigger').forEach(b=>b.onclick=e=>{if(innerWidth<=1080){e.preventDefault();b.parentElement.classList.toggle('open')}})})()</script>`;

function shell(html,path){let out=html;if(!out.includes('id="nyh47-css"'))out=out.replace(/<\/head>/i,css+'</head>');if(!out.includes('id="nyh47-header"'))out=out.replace(/<body([^>]*)>/i,`<body$1>${header}`);if(!out.includes('id="nyh47-footer"'))out=out.replace(/<\/body>/i,footer+js+'</body>');const canonical='https://newyorkhut.com'+path;if(/<link rel=["']canonical["'][^>]*>/i.test(out))out=out.replace(/<link rel=["']canonical["'][^>]*>/i,`<link rel="canonical" href="${canonical}">`);return out}

export default{async fetch(request,env,ctx){const url=new URL(request.url),path=url.pathname.replace(/\/+$/,'')||'/';if(path==='/api/version'||path==='/__version')return new Response(JSON.stringify({application:'NewYorkHUT.com',version:VERSION,deployedAt:'2026-07-21',features:['restored-sitewide-navigation','non-destructive-shell','desktop-dropdowns','mobile-navigation','contact','my-nyhut','complete-footer'],knowledgeBaseEntries:25},null,2),{headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store','x-newyorkhut-version':VERSION}});const response=await site.fetch(request,env,ctx),headers=new Headers(response.headers),type=headers.get('content-type')||'';headers.set('x-newyorkhut-version',VERSION);if(type.includes('text/html')){headers.set('cache-control','no-store, no-cache, must-revalidate, max-age=0');return new Response(shell(await response.text(),path),{status:response.status,statusText:response.statusText,headers})}return new Response(response.body,{status:response.status,statusText:response.statusText,headers})}};