import site from "./index-v18.js";
const ORDER="https://nyhut.com/";
const STATES={
"new-york-hut":["New York Highway Use Tax (HUT)","New York imposes a mileage-based highway use tax on qualifying vehicles operating on New York public highways.","The general gross-weight threshold is more than 18,000 pounds. Vehicle-specific credentials, returns, mileage records, and separate AFC rules may apply."],
"kentucky-kyu":["Kentucky KYU Weight-Distance Tax","Kentucky requires a KYU license for carriers operating qualified vehicles on Kentucky highways.","The current official threshold is a combined licensed weight greater than 59,999 pounds. Permanent accounts require quarterly filings, including zero-mile returns when no qualified travel occurs."],
"new-mexico-weight-distance":["New Mexico Weight-Distance Tax","New Mexico taxes most vehicles with a declared gross vehicle weight over 26,000 pounds for highway use in the state.","Carriers generally need annual vehicle permits and quarterly returns. A separate trip-tax workflow may apply to certain unregistered out-of-state commercial vehicles."],
"oregon-weight-mile":["Oregon Weight-Mile Tax","Oregon administers a weight-mile tax program based on declared operating weight and Oregon mileage.","Permanent enrollment, temporary weight-mile passes, reporting, payment, and detailed records are separate from IFTA and IRP. Oregon has announced structural changes effective July 1, 2027."],
"ifta":["International Fuel Tax Agreement (IFTA)","IFTA consolidates motor-fuel tax reporting among participating jurisdictions through a carrier's base jurisdiction.","IFTA addresses fuel-use tax allocation. It does not replace New York HUT, KYU, New Mexico weight-distance tax, Oregon weight-mile tax, vehicle registration, or operating authority."],
"irp":["International Registration Plan (IRP)","IRP apportions commercial-vehicle registration fees among participating jurisdictions based on fleet operation.","IRP is a registration system, not a fuel-tax or weight-distance-tax program. A properly apportioned plate does not by itself satisfy HUT, KYU, WDT, Oregon weight-mile, or IFTA obligations."],
"temporary-trip-permits":["Temporary Trip Permits","Temporary credentials can authorize limited operation when a carrier does not hold a permanent account or vehicle credential.","Each jurisdiction controls availability, timing, vehicle eligibility, trip limits, tax treatment, and whether a temporary permit substitutes for later filing obligations."]};
const COMP={
"hut-vs-ifta":["New York HUT vs. IFTA","HUT taxes qualifying New York highway mileage; IFTA allocates motor-fuel taxes among member jurisdictions.","A carrier may need both because they address different tax bases and different reporting systems."],
"hut-vs-irp":["New York HUT vs. IRP","HUT is a New York highway-use tax and credential program; IRP is apportioned commercial registration.","An apportioned plate does not eliminate New York HUT credential, return, tax, or recordkeeping requirements."],
"hut-vs-kyu":["New York HUT vs. Kentucky KYU","Both are state highway-use tax programs, but their weight thresholds, tax rates, credentials, filing systems, and temporary-permit rules differ.","Do not copy a fleet decision from one state to the other. Evaluate each jurisdiction independently."],
"hut-vs-new-mexico-wdt":["New York HUT vs. New Mexico Weight-Distance Tax","Both tax vehicle operation using mileage and weight concepts, but New York and New Mexico use different thresholds, permits, returns, and account structures.","IFTA registration does not replace either state-specific program."],
"hut-vs-oregon-weight-mile":["New York HUT vs. Oregon Weight-Mile Tax","New York and Oregon both impose state-specific highway-use taxes, but Oregon uses declared-weight enrollment and its own temporary-pass and reporting system.","Rates, report frequency, exclusions, bonds, and record rules must be verified separately."],
"trip-certificate-vs-permanent-registration":["HUT Trip Certificate vs. Permanent Registration","A trip certificate is designed for qualifying occasional operation; permanent registration is designed for recurring operation and ongoing account compliance.","Compare expected trip frequency, vehicle count, automotive-fuel transport, filing duties, and the annual trip-certificate limit before choosing."],
"hut-vs-temporary-trip-permit":["HUT Credential vs. Temporary Trip Permit","A New York HUT credential addresses New York highway-use tax compliance. A temporary registration or operating permit may address a different requirement.","The word permit is not interchangeable across programs. Confirm exactly which tax, registration, fuel, authority, or size-and-weight obligation each credential covers."]};
const C=`:root{--n:#082b4c;--b:#1768c5;--l:#dbe5ef;font-family:Inter,system-ui,sans-serif}*{box-sizing:border-box}body{margin:0;color:#122033;line-height:1.65}.w{width:min(1120px,calc(100% - 36px));margin:auto}.top{background:var(--n);color:#fff;padding:8px 0}header{background:#fff;border-bottom:1px solid var(--l);position:sticky;top:0;z-index:10}nav{min-height:72px;display:flex;justify-content:space-between;align-items:center;gap:16px}.brand,.links a,.btn{text-decoration:none}.brand{font-weight:900}.links{display:flex;gap:13px;align-items:center;font-weight:750}.btn{display:inline-flex;background:var(--b);color:#fff;padding:11px 16px;border-radius:10px;font-weight:850}.hero{padding:60px 0 48px;background:linear-gradient(#f9fcff,#edf5fb)}h1{font-size:clamp(2.5rem,5vw,4.4rem);line-height:1;letter-spacing:-.045em;color:var(--n);margin:12px 0 18px}h2,h3{color:var(--n)}.lead{font-size:1.15rem;color:#4e6074;max-width:860px}.crumb{font-size:.9rem;color:#5b6b7e}.crumb a,.card a,.side a{color:var(--b);text-decoration:none}.eye{font-size:.78rem;text-transform:uppercase;letter-spacing:.1em;font-weight:900;color:var(--b)}section{padding:62px 0}.grid{display:grid;grid-template-columns:repeat(3,1fr);gap:20px}.card,.side,.fact div{border:1px solid var(--l);border-radius:16px;padding:23px}.card{display:flex;flex-direction:column}.card p{color:#5b6b7e;flex:1}.article{display:grid;grid-template-columns:minmax(0,760px) 280px;gap:44px}.fact{display:grid;grid-template-columns:1fr 1fr;gap:14px;margin:24px 0}.note{background:#fff8e5;border-left:4px solid #f4b83f;padding:17px;margin:24px 0}.side{position:sticky;top:92px;height:max-content}.side a{display:block;font-weight:750;margin:10px 0}.cta{background:var(--n);color:#fff;border-radius:18px;padding:30px;margin-top:34px}.cta h2{color:#fff}footer{background:#071d33;color:#b7c6d6;padding:38px 0}@media(max-width:980px){.grid{grid-template-columns:1fr 1fr}.article{grid-template-columns:1fr}.side{position:static}.links a:not(.btn){display:none}}@media(max-width:620px){.grid,.fact{grid-template-columns:1fr}.w{width:min(100% - 24px,1120px)}h1{font-size:2.55rem}}`;
function H(){return `<div class="top"><div class="w">Independent trucking compliance guidance</div></div><header><nav class="w"><a class="brand" href="/">NewYorkHUT.com</a><div class="links"><a href="/guides">Guides</a><a href="/states">States</a><a href="/comparisons">Compare</a><a href="/university">University</a><a href="/tools">Tools</a><a class="btn" href="${ORDER}">Start Permit</a></div></nav></header>`}
function F(){return `<footer><div class="w"><strong>NewYorkHUT.com</strong><p>Private guidance and permit assistance. Not affiliated with any government agency.</p></div></footer>`}
function L(t,d,p,b,s=""){return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${t}</title><meta name="description" content="${d}"><meta name="robots" content="index,follow"><link rel="canonical" href="https://newyorkhut.com${p}"><meta property="og:title" content="${t}"><meta property="og:description" content="${d}"><style>${C}</style>${s}</head><body>${H()}${b}${F()}</body></html>`}
function hub(data,base,title,lead,eye){const cards=Object.entries(data).map(([s,v])=>`<article class="card"><h2>${v[0]}</h2><p>${v[1]}</p><a href="/${base}/${s}">Read guide →</a></article>`).join("");return L(title,lead,`/${base}`,`<main><section class="hero"><div class="w"><div class="crumb"><a href="/">Home</a> / ${title}</div><div class="eye">${eye}</div><h1>${title}</h1><p class="lead">${lead}</p></div></section><section><div class="w grid">${cards}</div></section></main>`,`<script type="application/ld+json">${JSON.stringify({"@context":"https://schema.org","@type":"CollectionPage","name":title,"url":`https://newyorkhut.com/${base}`})}</script>`)}
function page(data,base,s){const v=data[s],p=`/${base}/${s}`,rel=Object.entries(data).filter(([x])=>x!==s).slice(0,6).map(([x,y])=>`<a href="/${base}/${x}">${y[0]}</a>`).join("");const schema={"@context":"https://schema.org","@graph":[{"@type":"Article","headline":v[0],"description":v[1],"mainEntityOfPage":`https://newyorkhut.com${p}`},{"@type":"BreadcrumbList","itemListElement":[{"@type":"ListItem","position":1,"name":"Home","item":"https://newyorkhut.com/"},{"@type":"ListItem","position":2,"name":base,"item":`https://newyorkhut.com/${base}`},{"@type":"ListItem","position":3,"name":v[0],"item":`https://newyorkhut.com${p}`}]}]};return L(v[0],`${v[1]} Compare thresholds, credentials, returns, taxes, records, and temporary-operation options.`,p,`<main><section class="hero"><div class="w"><div class="crumb"><a href="/">Home</a> / <a href="/${base}">${base}</a> / ${v[0]}</div><div class="eye">Multi-jurisdiction compliance guide</div><h1>${v[0]}</h1><p class="lead">${v[1]}</p></div></section><section><div class="w article"><article><div class="fact"><div><strong>Core distinction</strong><p>${v[2]}</p></div><div><strong>Do not assume interchangeability</strong><p>Fuel tax, registration, highway-use tax, operating authority, and temporary credentials solve different compliance problems.</p></div></div><h2>Compare these elements</h2><ul><li>Vehicle and combination weight threshold</li><li>Permanent account versus temporary permit availability</li><li>Vehicle-specific credential or fleet-level registration</li><li>Mileage, fuel, declared weight, or apportioned-registration tax base</li><li>Return frequency, zero-return obligations, and payment deadlines</li><li>Vehicle inventory, trip records, fuel records, and retention period</li></ul><div class="note"><strong>Current-rule warning:</strong> rates, thresholds, filing systems, and temporary-permit rules can change. Verify the current official jurisdiction instructions before dispatch.</div><div class="cta"><h2>Build the right permit stack</h2><p>Use the service finder for New York HUT or continue to secure ordering.</p><a class="btn" href="/tools/service-finder">Service Finder</a> <a class="btn" href="${ORDER}">Start Permit</a></div></article><aside class="side"><h3>Related pages</h3>${rel}<h3>Compliance centers</h3><a href="/permit-types">Permit types</a><a href="/university">Compliance University</a><a href="/resources">Checklists</a></aside></div></section></main>`,`<script type="application/ld+json">${JSON.stringify(schema)}</script>`)}
function sitemap(base,data){const u=[`/${base}`,...Object.keys(data).map(x=>`/${base}/${x}`)];return `<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${u.map(x=>`<url><loc>https://newyorkhut.com${x}</loc><changefreq>monthly</changefreq></url>`).join("")}</urlset>`}
const HH={"content-type":"text/html; charset=UTF-8","cache-control":"public, max-age=300"};
export default{async fetch(r,e,c){const p=new URL(r.url).pathname.replace(/\/+$/g,"")||"/";if(p==="/states")return new Response(hub(STATES,"states","State Highway-Use and Truck Tax Guides","Compare New York HUT with other major state-specific trucking tax and registration systems.","State compliance center"),{headers:HH});if(p==="/comparisons")return new Response(hub(COMP,"comparisons","Truck Permit and Tax Comparisons","Understand which credentials overlap, which do not, and why one permit rarely replaces another.","Comparison authority center"),{headers:HH});if(p==="/sitemap-states.xml")return new Response(sitemap("states",STATES),{headers:{"content-type":"application/xml; charset=UTF-8"}});if(p==="/sitemap-comparisons.xml")return new Response(sitemap("comparisons",COMP),{headers:{"content-type":"application/xml; charset=UTF-8"}});if(p.startsWith("/states/")){const s=p.split("/").pop();if(STATES[s])return new Response(page(STATES,"states",s),{headers:HH});}if(p.startsWith("/comparisons/")){const s=p.split("/").pop();if(COMP[s])return new Response(page(COMP,"comparisons",s),{headers:HH});}return site.fetch(r,e,c)}};
