import site from "./index-v10.js";
const ORDER="https://nyhut.com/";
const V={
"semi-trucks":["Semi Trucks","Tractors and tractor-trailer combinations commonly exceed New York's HUT threshold and generally require vehicle-specific credentials before operation.","Use combined gross weight when the tractor operates with a trailer."],
"dump-trucks":["Dump Trucks","Dump trucks over the applicable threshold are generally subject to HUT unless a specific exclusion or exemption applies.","Construction work alone does not automatically exclude a dump truck."],
"box-trucks":["Box Trucks","A box truck may require HUT when gross weight exceeds 18,000 pounds, even when no CDL is required.","The CDL threshold is not the HUT threshold."],
"tow-trucks":["Tow Trucks","Tow trucks are not automatically excluded truck cranes and may require HUT based on weight and operation.","New York distinguishes regular towing vehicles from excluded truck cranes."],
"concrete-mixers":["Concrete Mixers","Concrete mixer trucks commonly exceed the HUT threshold and generally require registration.","A mixer is different from a qualifying concrete pump with no cargo capacity."],
"concrete-pumps":["Concrete Pumps","Some concrete pumps may be excluded when they meet New York's truck-crane definition and are used only as designed.","Mixed use or cargo capacity can change the result."],
"car-haulers":["Car Haulers","Car-hauling tractors and trucks generally require HUT when gross weight exceeds 18,000 pounds.","Evaluate the operating combination, not only the power unit."],
"tank-trucks":["Tank Trucks","Tank trucks follow normal HUT rules, with additional AFC and trip-certificate restrictions for automotive fuel.","HUT trip certificates are unavailable for automotive-fuel transport."],
"logging-trucks":["Logging Trucks","Logging trucks generally require HUT unless a narrowly defined exclusive-use exemption applies.","Farm exemptions depend on ownership, origin, destination, and exclusive use."],
"garbage-trucks":["Garbage Trucks","Garbage trucks are not categorically exempt; weight, ownership, control, and actual use determine the result.","Government-controlled vehicles may differ from private contractors."],
"buses":["Buses and Motorcoaches","Certain omnibuses may be excluded when engaged in qualifying passenger transportation under specified jurisdiction.","The exclusion depends on actual use and regulatory status."],
"bucket-trucks":["Bucket Trucks","Some aerial bucket trucks may qualify as excluded truck cranes when design and use requirements are met.","Carrying materials or other use can change the result."]};
const C=`:root{--n:#082b4c;--b:#1768c5;--l:#dbe5ef;--s:#f4f8fc;font-family:Inter,system-ui,sans-serif}*{box-sizing:border-box}body{margin:0;color:#122033;line-height:1.65}.w{width:min(1120px,calc(100% - 40px));margin:auto}a{color:inherit}.top{background:var(--n);color:#fff;padding:8px 0}header{position:sticky;top:0;background:#fff;border-bottom:1px solid var(--l)}nav{min-height:72px;display:flex;justify-content:space-between;align-items:center;gap:20px}.brand{font-weight:900;text-decoration:none}.links{display:flex;gap:17px;align-items:center;font-weight:750}.links a{text-decoration:none}.btn{display:inline-flex;background:var(--b);color:#fff;padding:11px 17px;border-radius:10px;text-decoration:none;font-weight:850}.hero{padding:62px 0 50px;background:linear-gradient(#f9fcff,#edf5fb)}h1{font-size:clamp(2.5rem,5vw,4.5rem);line-height:1;letter-spacing:-.045em;color:var(--n);margin:12px 0 18px}h2,h3{color:var(--n)}.lead{font-size:1.15rem;color:#4e6074;max-width:820px}.crumb{font-size:.9rem;color:#5b6b7e}.crumb a,.card a,.side a{color:var(--b);text-decoration:none}.eye{font-size:.78rem;text-transform:uppercase;letter-spacing:.1em;font-weight:900;color:var(--b);margin-top:14px}section{padding:64px 0}.grid{display:grid;grid-template-columns:repeat(3,1fr);gap:20px}.card{border:1px solid var(--l);border-radius:16px;padding:23px;display:flex;flex-direction:column}.card p{color:#5b6b7e;flex:1}.article{display:grid;grid-template-columns:minmax(0,760px) 280px;gap:46px}.content p,.content li{color:#46596d}.fact{display:grid;grid-template-columns:1fr 1fr;gap:14px;margin:24px 0}.fact div,.side{border:1px solid var(--l);border-radius:13px;padding:18px}.side{position:sticky;top:92px;height:max-content}.side a{display:block;font-weight:750;margin:10px 0}.note{border-left:4px solid #f4b83f;background:#fff8e5;padding:17px;margin:24px 0}.cta{background:var(--n);color:#fff;border-radius:18px;padding:30px;margin-top:34px}.cta h2{color:#fff}footer{background:#071d33;color:#b7c6d6;padding:38px 0}@media(max-width:900px){.grid{grid-template-columns:1fr 1fr}.article{grid-template-columns:1fr}.side{position:static}.links a:not(.btn){display:none}}@media(max-width:620px){.grid,.fact{grid-template-columns:1fr}.w{width:min(100% - 26px,1120px)}h1{font-size:2.6rem}}`;
function H(){return `<div class="top"><div class="w">Independent New York HUT guidance</div></div><header><nav class="w"><a class="brand" href="/">NewYorkHUT.com</a><div class="links"><a href="/guides">Guides</a><a href="/states">States</a><a href="/vehicles">Vehicles</a><a href="/tools">Tools</a><a class="btn" href="${ORDER}">Start Permit</a></div></nav></header>`}
function F(){return `<footer><div class="w"><strong>NewYorkHUT.com</strong><p>Private guidance and permit assistance. Not affiliated with New York State.</p></div></footer>`}
function L(t,d,p,b,s=""){return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${t}</title><meta name="description" content="${d}"><meta name="robots" content="index,follow"><link rel="canonical" href="https://newyorkhut.com${p}"><meta property="og:title" content="${t}"><meta property="og:description" content="${d}"><style>${C}</style>${s}</head><body>${H()}${b}${F()}</body></html>`}
function I(){const cards=Object.entries(V).map(([s,v])=>`<article class="card"><h2>${v[0]}</h2><p>${v[1]}</p><a href="/vehicles/${s}">View HUT guide →</a></article>`).join("");return L("New York HUT Requirements by Vehicle Type","New York HUT guidance for semi trucks, dump trucks, box trucks, tow trucks, buses, tank trucks, and other vehicles.","/vehicles",`<main><section class="hero"><div class="w"><div class="crumb"><a href="/">Home</a> / Vehicles</div><div class="eye">Vehicle authority center</div><h1>Does this vehicle need New York HUT?</h1><p class="lead">Gross weight, configuration, ownership, actual use, and specific exclusions or exemptions determine the answer.</p></div></section><section><div class="w grid">${cards}</div></section></main>`,`<script type="application/ld+json">${JSON.stringify({"@context":"https://schema.org","@type":"CollectionPage","name":"New York HUT Vehicle Guides","url":"https://newyorkhut.com/vehicles"})}</script>`)}
function P(s){const v=V[s],p=`/vehicles/${s}`;const rel=Object.entries(V).filter(([x])=>x!==s).slice(0,6).map(([x,y])=>`<a href="/vehicles/${x}">${y[0]}</a>`).join("");const schema={"@context":"https://schema.org","@graph":[{"@type":"Article","headline":`${v[0]} and New York HUT`,"description":v[1],"mainEntityOfPage":`https://newyorkhut.com${p}`},{"@type":"BreadcrumbList","itemListElement":[{"@type":"ListItem","position":1,"name":"Home","item":"https://newyorkhut.com/"},{"@type":"ListItem","position":2,"name":"Vehicles","item":"https://newyorkhut.com/vehicles"},{"@type":"ListItem","position":3,"name":v[0],"item":`https://newyorkhut.com${p}`}]}]};return L(`${v[0]} and New York HUT Requirements`,`${v[1]} Review weight, use, credential, and exemption questions before operating in New York.`,p,`<main><section class="hero"><div class="w"><div class="crumb"><a href="/">Home</a> / <a href="/vehicles">Vehicles</a> / ${v[0]}</div><div class="eye">Vehicle-specific guide</div><h1>${v[0]} and New York HUT</h1><p class="lead">${v[1]}</p></div></section><section><div class="w article"><article class="content"><h2>General threshold</h2><p>A HUT certificate is generally required for a truck, tractor, or other self-propelled vehicle with gross weight over 18,000 pounds, subject to reporting elections, exclusions, and exemptions.</p><div class="fact"><div><strong>Vehicle issue</strong><p>${v[2]}</p></div><div><strong>Credential timing</strong><p>A subject vehicle generally needs its certificate and decal before operating on New York public highways.</p></div></div><h2>Questions to answer</h2><ul><li>What is the gross weight alone or in combination?</li><li>Is the vehicle used exclusively for a specifically excluded or exempt purpose?</li><li>Is operation occasional or recurring?</li><li>Is the exact VIN associated with the correct carrier account?</li><li>Who will file returns and retain mileage records?</li></ul><div class="note"><strong>Do not rely on the vehicle label alone.</strong> Configuration and actual use can change the HUT result.</div><h2>Occasional operation</h2><p>A vehicle-specific trip certificate may be available instead of permanent registration, although automotive-fuel transportation has additional restrictions.</p><div class="cta"><h2>Confirm the correct workflow</h2><p>Use the service finder or continue to secure ordering.</p><a class="btn" href="/tools/service-finder">Service Finder</a> <a class="btn" href="${ORDER}">Start Permit</a></div></article><aside class="side"><h3>Other vehicles</h3>${rel}<h3>Related topics</h3><a href="/compare/hut-vs-ifta">HUT vs IFTA</a><a href="/guides/one-trip-to-new-york">One-trip operation</a><a href="/resources/new-registration-checklist">Registration checklist</a></aside></div></section></main>`,`<script type="application/ld+json">${JSON.stringify(schema)}</script>`)}
function S(){const u=["/vehicles",...Object.keys(V).map(x=>`/vehicles/${x}`)];return `<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${u.map(x=>`<url><loc>https://newyorkhut.com${x}</loc><changefreq>monthly</changefreq></url>`).join("")}</urlset>`}
const HH={"content-type":"text/html; charset=UTF-8","cache-control":"public, max-age=300"};
export default{async fetch(r,e,c){const p=new URL(r.url).pathname.replace(/\/+$/,"")||"/";if(p==="/vehicles")return new Response(I(),{headers:HH});if(p==="/sitemap-vehicles.xml")return new Response(S(),{headers:{"content-type":"application/xml; charset=UTF-8"}});if(p.startsWith("/vehicles/")){const s=p.split("/").pop();if(V[s])return new Response(P(s),{headers:HH});}return site.fetch(r,e,c)}};