import site from './index-v59.js';

const VERSION='v60';
const ORDER='https://www.nyhut.com/';
const ASK='/ask-hut-ai';
const MT903='https://www.tax.ny.gov/forms/current-forms/motor/mt903i.htm';
const WEBFILE='https://www.tax.ny.gov/bus/hut/webfile.htm';
const FILING='https://www.tax.ny.gov/pubs_and_bulls/tg_bulletins/hut/filing_requirements.htm';
const RECORDS='https://www.tax.ny.gov/pubs_and_bulls/tg_bulletins/hut/recordkeeping_requirements.htm';

const CSS=`<style id="nyh-v60-filing-css">
:root{--n:#082b4c;--b:#1768c5;--l:#d7e3ed;--m:#5b6f83;--p:#f3f8fc;--y:#fff8df;font-family:Inter,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}*{box-sizing:border-box}body{margin:0;color:#13263a;line-height:1.58}.w{width:min(1160px,calc(100% - 40px));margin:auto}header{position:sticky;top:0;z-index:9999;background:#fff;border-bottom:1px solid var(--l);box-shadow:0 4px 18px rgba(8,43,76,.06)}.nav{min-height:76px;display:flex;align-items:center;justify-content:space-between;gap:18px}.brand{font-weight:950;color:var(--n);text-decoration:none;font-size:1.15rem}.links{display:flex;gap:8px;flex-wrap:wrap}.links a{padding:9px 13px;border:1px solid #b8cad9;border-radius:10px;text-decoration:none;color:var(--n);font-weight:850}.links .order{background:var(--b);color:#fff;border-color:var(--b)}.hero{padding:58px 0 44px;background:linear-gradient(135deg,#f9fcff,#eaf4fc)}h1{font-size:clamp(2.3rem,5vw,4rem);line-height:1.03;letter-spacing:-.04em;color:var(--n);margin:10px 0 16px}h2,h3{color:var(--n)}.lead{max-width:930px;color:#496078;font-size:1.08rem}.eyebrow{font-size:.76rem;text-transform:uppercase;letter-spacing:.09em;font-weight:900;color:var(--b)}.section{padding:48px 0 72px}.grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:20px}.card,.panel{border:1px solid var(--l);border-radius:20px;padding:24px;background:#fff;box-shadow:0 10px 34px rgba(8,43,76,.06)}.card p,.card li{color:var(--m)}.btn{display:inline-flex;align-items:center;justify-content:center;margin:10px 8px 0 0;padding:12px 16px;border-radius:10px;background:var(--b);color:#fff;text-decoration:none;font-weight:900}.secondary{background:#fff;color:var(--b);border:1px solid var(--b)}.notice{background:var(--y);border-left:4px solid #e2a500;padding:16px;border-radius:8px;margin:20px 0}.steps{padding-left:22px}.steps li{margin:10px 0}.related{display:flex;gap:10px;flex-wrap:wrap;margin-top:20px}.related a{padding:9px 12px;border:1px solid var(--l);border-radius:999px;text-decoration:none;color:var(--n);font-weight:800}.source{background:var(--p);border:1px solid #cfe0ee;border-radius:18px;padding:22px;margin-top:24px}.faq details{border-bottom:1px solid var(--l);padding:14px 0}.faq summary{font-weight:850;color:var(--n);cursor:pointer}.table{width:100%;border-collapse:collapse;margin-top:14px}.table th,.table td{border-bottom:1px solid var(--l);padding:12px;text-align:left}.table th{color:var(--n)}@media(max-width:800px){.grid{grid-template-columns:1fr}.nav{display:block;padding:12px 0}.brand{display:block;margin-bottom:10px}.links{display:grid;grid-template-columns:repeat(2,1fr)}.links a{text-align:center}.links .order{grid-column:1/-1}.w{width:min(100% - 24px,1160px)}}
</style>`;

function header(){return `<header><div class="w nav"><a class="brand" href="/">NewYorkHUT.com</a><nav class="links" aria-label="Primary navigation"><a href="/learn">Learn</a><a href="/mt-903-filing-center">MT-903 Filing</a><a href="/vehicle-lifecycle">Vehicle Changes</a><a href="/tools">Tools</a><a href="${ASK}">Ask HUT AI</a><a class="order" href="${ORDER}">Go to NYHUT</a></nav></div></header>`}
function shell(title,description,path,body){return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${title}</title><meta name="description" content="${description}"><link rel="canonical" href="https://newyorkhut.com${path}">${CSS}</head><body>${header()}${body}</body></html>`}
function related(){return `<div class="related"><a href="/mt-903-filing-center">MT-903 Filing Center</a><a href="/tools/mt903-due-date">Due Date Tool</a><a href="/tools/hut-tax-estimator">Tax Estimator</a><a href="${ASK}">Ask HUT AI</a><a href="${ORDER}">Open NYHUT</a></div>`}

const pages={
'/learn/what-is-form-mt-903':{title:'What Is Form MT-903?',desc:'Understand who files Form MT-903, what it reports, and how New York Highway Use Tax returns work.',quick:'Form MT-903 is New York’s Highway Use Tax Return. A carrier generally must file it when issued a HUT certificate or when operating certain taxable vehicles in New York. A return is still required for a period with no New York activity.',steps:['Confirm the filing period shown for the HUT account.','Collect vehicle-by-vehicle mileage and supporting records.','Use the reporting method selected for that calendar year.','Calculate tax for each applicable vehicle and mileage category.','File through HUT Web File or submit the current paper form.','Retain the filed return, confirmation, and supporting records.'],mistakes:['Assuming no activity means no return is required.','Using a different tax method midyear.','Filing totals without vehicle-level supporting records.'],source:MT903},
'/learn/who-must-file-mt-903':{title:'Who Must File an MT-903 Return?',desc:'Learn when a New York HUT return is required, including no-activity periods and issued certificates.',quick:'You generally must file if you were issued a HUT certificate of registration or operated certain taxable motor vehicles in New York. Certificate holders must usually file even when no tax is due or another party will pay the tax.',steps:['Check whether a HUT certificate was active during the reporting period.','Check whether taxable New York operation occurred.','Confirm whether the account was assigned monthly, quarterly, or annual filing.','File a no-activity return when required.','Use a final return only when permanently discontinuing the entire HUT business.'],mistakes:['Skipping a return because the truck did not enter New York.','Assuming a leased-vehicle arrangement removes the filing duty.','Marking a return final when only one vehicle was sold.'],source:FILING},
'/learn/mt-903-filing-deadlines-and-frequency':{title:'MT-903 Filing Deadlines and Filing Frequency',desc:'Review monthly, quarterly, and annual New York HUT filing periods and due dates.',quick:'New HUT accounts generally begin as quarterly filers. Returns are due on the last day of the month following the reporting period. New York may later reclassify the account based on prior-year HUT liability.',steps:['Confirm the filing frequency displayed in HUT Web File or the Tax Department notice.','Identify the correct reporting period.','File and pay by the last day of the following month.','Move a weekend or legal-holiday deadline to the next business day.','Review annual reclassification notices before the next filing.'],mistakes:['Assuming every HUT account remains quarterly forever.','Using calendar-quarter sales-tax deadlines.','Waiting for a paper notice when Web File already displays the assigned frequency.'],source:WEBFILE},
'/learn/new-york-hut-taxable-miles':{title:'New York HUT Taxable Miles Guide',desc:'Understand the mileage categories needed to prepare a New York MT-903 return.',quick:'HUT is based on qualifying mileage traveled on New York public highways. Records must separate taxable operations from nontaxable operations and, under the gross-weight method, distinguish laden and unladen New York miles.',steps:['Record every trip by vehicle and date.','Separate New York miles from miles outside New York.','Separate laden and unladen New York miles when using the gross-weight method.','Identify qualifying toll-paid New York State Thruway mileage.','Reconcile trip records to monthly vehicle summaries.','Use the supported totals in the MT-903 calculation.'],mistakes:['Reporting dispatch estimates without daily trip support.','Treating all New York mileage as the same category.','Claiming Thruway mileage without toll or other supporting records.'],source:RECORDS},
'/learn/hut-recordkeeping-requirements':{title:'New York HUT Recordkeeping Requirements',desc:'Learn what daily trip, vehicle, mileage, toll, and supporting records New York requires for HUT.',quick:'Every carrier subject to HUT must keep daily records for each registered truck or tractor. Records must support actual mileage and generally must be retained for at least four years from the return due date or filing date, whichever is later.',steps:['Maintain certificate number, plate, VIN, and owner information for each vehicle.','Record trip dates, origins, destinations, and round trips.','Record New York and non-New York mileage.','Record laden, unladen, and qualifying toll-paid Thruway mileage as applicable.','Prepare monthly summaries by vehicle.','Retain source documents such as logs, bills of lading, dispatch sheets, invoices, and toll records.'],mistakes:['Keeping only quarterly totals.','Failing to connect toll receipts to the correct vehicle and trip.','Deleting electronic records before the retention period ends.'],source:RECORDS},
'/learn/amended-final-and-no-activity-mt-903-returns':{title:'Amended, Final, and No-Activity MT-903 Returns',desc:'Understand the difference between amended, final, and no-activity New York HUT returns.',quick:'A no-activity return reports an open filing period with no New York activity. An amended return corrects a previously filed return. A final return is only for permanently discontinuing the entire HUT business.',steps:['Use no-activity status when the account remains open but had no reportable operations.','Use amended status to correct a previously filed period.','Use final status only when permanently ending all HUT operations.','Resolve outstanding bills and delinquent returns.','For a final return, follow the certificate and decal surrender instructions.','Retain confirmation and account-closure records.'],mistakes:['Filing final because one vehicle was sold.','Assuming a final return erases old bills or delinquencies.','Failing to file a required no-activity return.'],source:MT903}
};

function guide(path,data){const body=`<main><section class="hero"><div class="w"><div class="eyebrow">MT-903 filing guide</div><h1>${data.title}</h1><p class="lead">${data.quick}</p></div></section><section class="section"><div class="w"><div class="grid"><article class="card"><h2>Quick answer</h2><p>${data.quick}</p><h2>Step-by-step</h2><ol class="steps">${data.steps.map(x=>`<li>${x}</li>`).join('')}</ol></article><article class="card"><h2>Common mistakes</h2><ul>${data.mistakes.map(x=>`<li>${x}</li>`).join('')}</ul><div class="notice"><strong>Important:</strong> Use the filing frequency and reporting method assigned to the account. Verify current New York instructions before submitting a return.</div><a class="btn" href="${ORDER}">Prepare or manage filing in NYHUT →</a><a class="btn secondary" href="${ASK}">Ask HUT AI →</a></article></div><div class="source"><h2>Official reference</h2><p>This guide is based on current New York Tax Department HUT filing and recordkeeping guidance.</p><a class="btn" href="${data.source}" target="_blank" rel="noopener">View official guidance →</a>${related()}</div></div></section></main>`;return shell(`${data.title} | NewYorkHUT.com`,data.desc,path,body)}

function hub(){const cards=[
['What Is Form MT-903?','/learn/what-is-form-mt-903','Understand the return, filing methods, and the basic filing workflow.'],
['Who Must File?','/learn/who-must-file-mt-903','Certificate holders, taxable operators, and required no-activity returns.'],
['Deadlines and Frequency','/learn/mt-903-filing-deadlines-and-frequency','Monthly, quarterly, and annual periods with standard due dates.'],
['Taxable Miles','/learn/new-york-hut-taxable-miles','Separate New York, laden, unladen, and qualifying Thruway mileage.'],
['Recordkeeping','/learn/hut-recordkeeping-requirements','Daily trip records, monthly summaries, toll support, and four-year retention.'],
['Amended, Final, and No Activity','/learn/amended-final-and-no-activity-mt-903-returns','Choose the correct return type and avoid closing the account incorrectly.']
];const body=`<main><section class="hero"><div class="w"><div class="eyebrow">New York HUT return guidance</div><h1>MT-903 Filing Center</h1><p class="lead">Use this filing center to understand who must file, when returns are due, what mileage records are required, and how to handle no-activity, amended, and final returns.</p></div></section><section class="section"><div class="w"><div class="grid">${cards.map(c=>`<article class="card"><h2>${c[0]}</h2><p>${c[2]}</p><a class="btn" href="${c[1]}">Open guide →</a></article>`).join('')}</div><div class="source"><h2>Quarterly filing schedule</h2><table class="table"><tr><th>Quarter</th><th>Standard due date</th></tr><tr><td>January–March</td><td>April 30</td></tr><tr><td>April–June</td><td>July 31</td></tr><tr><td>July–September</td><td>October 31</td></tr><tr><td>October–December</td><td>January 31</td></tr></table><p>New accounts generally begin quarterly unless New York assigns a different frequency. Web File displays the account’s current filing frequency.</p><a class="btn" href="/tools/mt903-due-date">Use Due Date Calculator →</a><a class="btn secondary" href="${ORDER}">Open NYHUT Filing Center →</a>${related()}</div></div></section></main>`;return shell('New York MT-903 Filing Center','Guides for New York HUT filing requirements, deadlines, taxable miles, recordkeeping, and special return types.','/mt-903-filing-center',body)}

function injectLinks(html){if(html.includes('MT-903 Filing Center'))return html;const block=`<section class="panel" style="margin:24px auto;width:min(1100px,calc(100% - 40px))"><h2>MT-903 filing guidance</h2><p>Review filing requirements, deadlines, taxable mileage, records, and special return types.</p><a class="btn" href="/mt-903-filing-center">Open MT-903 Filing Center →</a></section>`;let out=html;if(!out.includes('nyh-v60-filing-css'))out=out.replace(/<\/head>/i,`${CSS}</head>`);return out.replace(/<\/main>/i,`${block}</main>`)}

export default{async fetch(request,env,ctx){const url=new URL(request.url);const path=url.pathname.replace(/\/+$/,'')||'/';if(path==='/mt-903-filing-center'||path==='/mt903-filing-center')return new Response(hub(),{headers:{'content-type':'text/html; charset=utf-8','cache-control':'no-store','x-newyorkhut-version':VERSION,'x-newyorkhut-feature':'mt903-filing-center-v60'}});if(pages[path])return new Response(guide(path,pages[path]),{headers:{'content-type':'text/html; charset=utf-8','cache-control':'no-store','x-newyorkhut-version':VERSION,'x-newyorkhut-feature':'mt903-filing-guides-v60'}});const response=await site.fetch(request,env,ctx);if((path==='/learn'||path==='/ask-hut-ai'||path==='/tools')&&(response.headers.get('content-type')||'').includes('text/html')){const headers=new Headers(response.headers);headers.set('cache-control','no-store');headers.set('x-newyorkhut-version',VERSION);return new Response(injectLinks(await response.text()),{status:response.status,headers})}return response}};