import site from "./index-v23.js";
const ORDER="https://nyhut.com/";
const TERMS={
"hut":["HUT — Highway Use Tax","New York tax imposed on qualifying motor vehicles using the state's public highways, generally based on mileage and vehicle weight."],
"afc":["AFC — Automotive Fuel Carrier","A registration category for qualifying vehicles transporting automotive fuel in New York."],
"certificate-of-registration":["Certificate of Registration","The vehicle-specific credential authorizing qualifying HUT or AFC operation."],
"hut-decal":["HUT Decal","The vehicle-specific decal issued with a permanent HUT or AFC certificate of registration."],
"trip-certificate":["Trip Certificate","A temporary vehicle-specific HUT credential for qualifying occasional New York operation."],
"taxable-mileage":["Taxable Mileage","New York public-highway mileage included in the selected HUT reporting method after supported exclusions or adjustments."],
"gross-weight-method":["Gross Weight Method","A HUT calculation method based on vehicle gross weight and applicable laden or unladen mileage categories."],
"unloaded-weight-method":["Unloaded Weight Method","A HUT calculation method based on the unloaded weight of the truck or tractor."],
"ifta":["IFTA — International Fuel Tax Agreement","A multi-jurisdiction fuel-tax reporting system that does not replace New York HUT."],
"irp":["IRP — International Registration Plan","A system for apportioned commercial-vehicle registration that does not replace New York HUT."],
"kyu":["KYU Number","Kentucky's weight-distance tax credential for qualifying heavy vehicles."],
"weight-distance-tax":["Weight-Distance Tax","A tax generally calculated using vehicle weight and miles traveled within a jurisdiction."],
"oscar":["OSCAR","New York's One Stop Credentialing and Registration system for certain motor-carrier credentials."],
"mt-903":["Form MT-903","New York's Highway Use Tax Return used for paper filing when HUT Web File is not used."],
"tmt-1":["Form TMT-1","Application for HUT and AFC certificates of registration and decals."],
"tmt-39":["Form TMT-39","New account application for New York HUT and AFC."],
"tmt-334":["Form TMT-334","Application for duplicate or replacement HUT or AFC certificates and decals."]};
const FORMS={
"mt-903":["MT-903 — Highway Use Tax Return","Paper HUT return and instructions.","https://www.tax.ny.gov/forms/current-forms/motor/mt903.htm"],
"tmt-39":["TMT-39 — New HUT/AFC Account","Creates a new Highway Use Tax or Automotive Fuel Carrier account.","https://www.tax.ny.gov/forms/current-forms/motor/tmt39.htm"],
"tmt-1":["TMT-1 — Certificates and Decals","Applies for HUT or AFC certificates of registration and decals.","https://www.tax.ny.gov/forms/current-forms/motor/tmt1.htm"],
"tmt-334":["TMT-334 — Replacement Credentials","Requests duplicate or replacement HUT/AFC certificates or decals.","https://www.tax.ny.gov/forms/current-forms/motor/tmt334.htm"],
"web-file":["HUT Web File","Official online return-filing and payment system.","https://www.tax.ny.gov/bus/hut/webfile.htm"],
"hut-home":["Official Highway Use Tax Center","Primary New York Tax Department HUT resource page.","https://www.tax.ny.gov/bus/hut/huidx.htm"],
"forms-index":["Highway Use and Fuel Use Forms","Current official HUT, AFC, and IFTA form index.","https://www.tax.ny.gov/forms/highway_use_fuel_use_tax.htm"],
"bulletins":["Highway Use Tax Bulletins","Official HUT bulletins covering registration, filing, records, exemptions, tax calculation, and enforcement.","https://www.tax.ny.gov/pubs_and_bulls/publications/highway_use_pubs.htm"]};
const CSS=`:root{--n:#082b4c;--b:#1768c5;--l:#dbe5ef;--s:#f4f8fc;font-family:Inter,system-ui,sans-serif}*{box-sizing:border-box}body{margin:0;color:#122033;line-height:1.65}.w{width:min(1120px,calc(100% - 36px));margin:auto}.top{background:var(--n);color:#fff;padding:8px 0}header{background:#fff;border-bottom:1px solid var(--l);position:sticky;top:0;z-index:10}nav{min-height:72px;display:flex;justify-content:space-between;align-items:center;gap:18px}.brand,.links a,.btn{text-decoration:none}.brand{font-weight:900}.links{display:flex;gap:13px;align-items:center;font-weight:750}.btn{display:inline-flex;background:var(--b);color:#fff;padding:11px 16px;border-radius:10px;font-weight:850}.hero{padding:60px 0 48px;background:linear-gradient(#f9fcff,#edf5fb)}h1{font-size:clamp(2.45rem,5vw,4.3rem);line-height:1;letter-spacing:-.045em;color:var(--n);margin:12px 0 18px}h2,h3{color:var(--n)}.lead{font-size:1.15rem;color:#4e6074;max-width:850px}.crumb{font-size:.9rem;color:#5b6b7e}.crumb a,.card a{color:var(--b);text-decoration:none}.eye{font-size:.78rem;text-transform:uppercase;letter-spacing:.1em;font-weight:900;color:var(--b)}section{padding:62px 0}.grid{display:grid;grid-template-columns:repeat(3,1fr);gap:20px}.card{border:1px solid var(--l);border-radius:16px;padding:23px;display:flex;flex-direction:column}.card p{color:#5b6b7e;flex:1}.article{max-width:820px}.note{background:#fff8e5;border-left:4px solid #f4b83f;padding:17px;margin:24px 0}.cta{background:var(--n);color:#fff;border-radius:18px;padding:30px;margin-top:34px}.cta h2{color:#fff}footer{background:#071d33;color:#b7c6d6;padding:38px 0}@media(max-width:900px){.grid{grid-template-columns:1fr 1fr}.links a:not(.btn){display:none}}@media(max-width:620px){.grid{grid-template-columns:1fr}.w{width:min(100% - 24px,1120px)}h1{font-size:2.5rem}}`;
function H(){return `<div class="top"><div class="w">Independent New York HUT guidance</div></div><header><nav class="w"><a class="brand" href="/">NewYorkHUT.com</a><div class="links"><a href="/glossary">Glossary</a><a href="/official-resources">Official Resources</a><a href="/assistant">Permit Assistant</a><a href="/guides">Guides</a><a class="btn" href="${ORDER}">Start Permit</a></div></nav></header>`}
function F(){return `<footer><div class="w"><strong>NewYorkHUT.com</strong><p>Private guidance and permit assistance. Not affiliated with New York State.</p></div></footer>`}
function L(t,d,p,b,s=""){return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${t}</title><meta name="description" content="${d}"><meta name="robots" content="index,follow"><link rel="canonical" href="https://newyorkhut.com${p}"><meta property="og:title" content="${t}"><meta property="og:description" content="${d}"><style>${CSS}</style>${s}</head><body>${H()}${b}${F()}</body></html>`}
function glossary(){const cards=Object.entries(TERMS).map(([s,v])=>`<article class="card"><h2>${v[0]}</h2><p>${v[1]}</p><a href="/glossary/${s}">View definition →</a></article>`).join("");return L("New York HUT Glossary","Definitions of New York HUT, AFC, IFTA, IRP, certificates, decals, mileage methods, forms, and motor-carrier compliance terms.","/glossary",`<main><section class="hero"><div class="w"><div class="crumb"><a href="/">Home</a> / Glossary</div><div class="eye">Compliance terminology</div><h1>New York HUT glossary and acronym center</h1><p class="lead">Clear definitions for the credentials, tax methods, forms, and interstate programs carriers encounter.</p></div></section><section><div class="w grid">${cards}</div></section></main>`,`<script type="application/ld+json">${JSON.stringify({"@context":"https://schema.org","@type":"DefinedTermSet","name":"New York HUT Glossary","url":"https://newyorkhut.com/glossary"})}</script>`)}
function term(s){const v=TERMS[s],p=`/glossary/${s}`;return L(v[0],v[1],p,`<main><section class="hero"><div class="w"><div class="crumb"><a href="/">Home</a> / <a href="/glossary">Glossary</a> / ${v[0]}</div><div class="eye">Defined compliance term</div><h1>${v[0]}</h1><p class="lead">${v[1]}</p></div></section><section><div class="w article"><h2>Why it matters</h2><p>This term affects how a carrier evaluates registration, filing, mileage records, tax calculation, or multistate compliance. Similar credentials often address different legal obligations and should not be treated as interchangeable.</p><div class="note"><strong>Verification rule:</strong> confirm the current official definition and the exact vehicle, account, trip, weight, and use before acting.</div><div class="cta"><h2>Find the right workflow</h2><a class="btn" href="/assistant">Use Permit Assistant</a></div></div></section></main>`,`<script type="application/ld+json">${JSON.stringify({"@context":"https://schema.org","@type":"DefinedTerm","name":v[0],"description":v[1],"url":`https://newyorkhut.com${p}`})}</script>`)}
function resources(){const cards=Object.values(FORMS).map(v=>`<article class="card"><h2>${v[0]}</h2><p>${v[1]}</p><a href="${v[2]}" rel="noopener noreferrer">Open official source ↗</a></article>`).join("");return L("Official New York HUT Forms and Sources","Current official New York HUT forms, filing tools, tax bulletins, registration resources, and replacement-credential links.","/official-resources",`<main><section class="hero"><div class="w"><div class="crumb"><a href="/">Home</a> / Official Resources</div><div class="eye">Source library</div><h1>Official New York HUT forms and verification sources</h1><p class="lead">Use the New York Tax Department as the final source for current forms, filing instructions, deadlines, and program rules.</p></div></section><section><div class="w"><div class="note"><strong>Check revision dates.</strong> Forms, instructions, fees, rates, and online workflows can change. Open the official source before filing or ordering.</div><div class="grid">${cards}</div></div></section></main>`,`<script type="application/ld+json">${JSON.stringify({"@context":"https://schema.org","@type":"CollectionPage","name":"Official New York HUT Forms and Sources","url":"https://newyorkhut.com/official-resources"})}</script>`)}
function map(base,keys){const u=[`/${base}`,...keys.map(x=>`/${base}/${x}`)];return `<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${u.map(x=>`<url><loc>https://newyorkhut.com${x}</loc><changefreq>monthly</changefreq></url>`).join("")}</urlset>`}
const MAPS=["sitemap-guides.xml","sitemap-vehicles.xml","sitemap-weight.xml","sitemap-exemptions.xml","sitemap-cost.xml","sitemap-tools.xml","sitemap-resources.xml","sitemap-industries.xml","sitemap-permit-types.xml","sitemap-university.xml","sitemap-states.xml","sitemap-comparisons.xml","sitemap-filing.xml","sitemap-faq.xml","sitemap-violations.xml","sitemap-calculators.xml","sitemap-assistant.xml","sitemap-services.xml","sitemap-glossary.xml","sitemap-official-resources.xml"];
const HH={"content-type":"text/html; charset=UTF-8","cache-control":"public, max-age=300"};
export default{async fetch(r,e,c){const p=new URL(r.url).pathname.replace(/\/+$/g,"")||"/";if(p==="/glossary")return new Response(glossary(),{headers:HH});if(p.startsWith("/glossary/")){const s=p.split("/").pop();if(TERMS[s])return new Response(term(s),{headers:HH})}if(p==="/official-resources")return new Response(resources(),{headers:HH});if(p==="/sitemap-glossary.xml")return new Response(map("glossary",Object.keys(TERMS)),{headers:{"content-type":"application/xml; charset=UTF-8"}});if(p==="/sitemap-official-resources.xml")return new Response(map("official-resources",[]),{headers:{"content-type":"application/xml; charset=UTF-8"}});if(p==="/sitemap.xml")return new Response(`<?xml version="1.0" encoding="UTF-8"?><sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${MAPS.map(x=>`<sitemap><loc>https://newyorkhut.com/${x}</loc></sitemap>`).join("")}</sitemapindex>`,{headers:{"content-type":"application/xml; charset=UTF-8"}});return site.fetch(r,e,c)}};